// automatically generated by the FlatBuffers compiler, do not modify
// ignore_for_file: unused_import, unused_field, unused_element, unused_local_variable, constant_identifier_names

import 'dart:typed_data' show Uint8List;
import 'package:flat_buffers/flat_buffers.dart' as fb;

class Oklab {
  Oklab._(this._bc, this._bcOffset);

  static const fb.Reader<Oklab> reader = _OklabReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  double get l => const fb.Float64Reader().read(_bc, _bcOffset + 0);
  double get a => const fb.Float64Reader().read(_bc, _bcOffset + 8);
  double get b => const fb.Float64Reader().read(_bc, _bcOffset + 16);

  @override
  String toString() {
    return 'Oklab{l: ${l}, a: ${a}, b: ${b}}';
  }
}

class _OklabReader extends fb.StructReader<Oklab> {
  const _OklabReader();

  @override
  int get size => 24;

  @override
  Oklab createObject(fb.BufferContext bc, int offset) => Oklab._(bc, offset);
}

class OklabBuilder {
  OklabBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  int finish(double l, double a, double b) {
    fbBuilder.putFloat64(b);
    fbBuilder.putFloat64(a);
    fbBuilder.putFloat64(l);
    return fbBuilder.offset;
  }
}

class OklabObjectBuilder extends fb.ObjectBuilder {
  final double _l;
  final double _a;
  final double _b;

  OklabObjectBuilder({required double l, required double a, required double b})
    : _l = l,
      _a = a,
      _b = b;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    fbBuilder.putFloat64(_b);
    fbBuilder.putFloat64(_a);
    fbBuilder.putFloat64(_l);
    return fbBuilder.offset;
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}

class NamedColorsCacheEntry {
  NamedColorsCacheEntry._(this._bc, this._bcOffset);
  factory NamedColorsCacheEntry(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<NamedColorsCacheEntry> reader =
      _NamedColorsCacheEntryReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  int get argb => const fb.Uint32Reader().vTableGet(_bc, _bcOffset, 4, 0);
  Oklab? get oklab => Oklab.reader.vTableGetNullable(_bc, _bcOffset, 6);
  List<NamedColorIdentity>? get identities =>
      const fb.ListReader<NamedColorIdentity>(
        NamedColorIdentity.reader,
      ).vTableGetNullable(_bc, _bcOffset, 8);

  @override
  String toString() {
    return 'NamedColorsCacheEntry{argb: ${argb}, oklab: ${oklab}, identities: ${identities}}';
  }
}

class _NamedColorsCacheEntryReader
    extends fb.TableReader<NamedColorsCacheEntry> {
  const _NamedColorsCacheEntryReader();

  @override
  NamedColorsCacheEntry createObject(fb.BufferContext bc, int offset) =>
      NamedColorsCacheEntry._(bc, offset);
}

class NamedColorsCacheEntryBuilder {
  NamedColorsCacheEntryBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(3);
  }

  int addArgb(int? argb) {
    fbBuilder.addUint32(0, argb);
    return fbBuilder.offset;
  }

  int addOklab(int offset) {
    fbBuilder.addStruct(1, offset);
    return fbBuilder.offset;
  }

  int addIdentitiesOffset(int? offset) {
    fbBuilder.addOffset(2, offset);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class NamedColorsCacheEntryObjectBuilder extends fb.ObjectBuilder {
  final int? _argb;
  final OklabObjectBuilder? _oklab;
  final List<NamedColorIdentityObjectBuilder>? _identities;

  NamedColorsCacheEntryObjectBuilder({
    int? argb,
    OklabObjectBuilder? oklab,
    List<NamedColorIdentityObjectBuilder>? identities,
  }) : _argb = argb,
       _oklab = oklab,
       _identities = identities;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? identitiesOffset = _identities == null
        ? null
        : fbBuilder.writeList(
            _identities!.map((b) => b.getOrCreateOffset(fbBuilder)).toList(),
          );
    fbBuilder.startTable(3);
    fbBuilder.addUint32(0, _argb);
    if (_oklab != null) {
      fbBuilder.addStruct(1, _oklab!.finish(fbBuilder));
    }
    fbBuilder.addOffset(2, identitiesOffset);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}

class NamedColorsCache {
  NamedColorsCache._(this._bc, this._bcOffset);
  factory NamedColorsCache(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<NamedColorsCache> reader = _NamedColorsCacheReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  List<NamedColorsCacheEntry>? get entries =>
      const fb.ListReader<NamedColorsCacheEntry>(
        NamedColorsCacheEntry.reader,
      ).vTableGetNullable(_bc, _bcOffset, 4);

  @override
  String toString() {
    return 'NamedColorsCache{entries: ${entries}}';
  }
}

class _NamedColorsCacheReader extends fb.TableReader<NamedColorsCache> {
  const _NamedColorsCacheReader();

  @override
  NamedColorsCache createObject(fb.BufferContext bc, int offset) =>
      NamedColorsCache._(bc, offset);
}

class NamedColorsCacheBuilder {
  NamedColorsCacheBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(1);
  }

  int addEntriesOffset(int? offset) {
    fbBuilder.addOffset(0, offset);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class NamedColorsCacheObjectBuilder extends fb.ObjectBuilder {
  final List<NamedColorsCacheEntryObjectBuilder>? _entries;

  NamedColorsCacheObjectBuilder({
    List<NamedColorsCacheEntryObjectBuilder>? entries,
  }) : _entries = entries;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? entriesOffset = _entries == null
        ? null
        : fbBuilder.writeList(
            _entries!.map((b) => b.getOrCreateOffset(fbBuilder)).toList(),
          );
    fbBuilder.startTable(1);
    fbBuilder.addOffset(0, entriesOffset);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}

class NamedColorIdentity {
  NamedColorIdentity._(this._bc, this._bcOffset);
  factory NamedColorIdentity(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<NamedColorIdentity> reader =
      _NamedColorIdentityReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  String? get name =>
      const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 4);

  @override
  String toString() {
    return 'NamedColorIdentity{name: ${name}}';
  }
}

class _NamedColorIdentityReader extends fb.TableReader<NamedColorIdentity> {
  const _NamedColorIdentityReader();

  @override
  NamedColorIdentity createObject(fb.BufferContext bc, int offset) =>
      NamedColorIdentity._(bc, offset);
}

class NamedColorIdentityBuilder {
  NamedColorIdentityBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(1);
  }

  int addNameOffset(int? offset) {
    fbBuilder.addOffset(0, offset);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class NamedColorIdentityObjectBuilder extends fb.ObjectBuilder {
  final String? _name;

  NamedColorIdentityObjectBuilder({String? name}) : _name = name;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? nameOffset = _name == null
        ? null
        : fbBuilder.writeString(_name!);
    fbBuilder.startTable(1);
    fbBuilder.addOffset(0, nameOffset);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
