name: lz4_ffi
description: FFI bindings for the LZ4 compression algorithm library.
version: 1.0.0-dev.5
homepage: https://github.com/deminearchiver/dart-flutter-packages
repository: https://github.com/deminearchiver/dart-flutter-packages/tree/main/packages/lz4_ffi
issue_tracker: https://github.com/deminearchiver/dart-flutter-packages/issues
resolution: workspace

environment:
  sdk: ^3.11.0

dependencies:
  code_assets: ^1.0.0
  crypto: ^3.0.7
  ffi: ^2.2.0
  hooks: ^1.0.2
  meta: ^1.17.0
  native_toolchain_c: ^0.17.5

dev_dependencies:
  deminearchiver_lints: ^2.1.2
  ffigen: ^20.1.1
