name: deminearchiver_lints
description: Opinionated lints for Dart and Flutter projects.
version: 3.0.1
homepage: https://github.com/deminearchiver/dart-flutter-packages
repository: https://github.com/deminearchiver/dart-flutter-packages/tree/main/packages/deminearchiver_lints
issue_tracker: https://github.com/deminearchiver/dart-flutter-packages/issues
topics: [analysis, analyzer, code-style, lint, lints]
resolution: workspace

environment:
  sdk: ^3.13.0
