name: deminearchiver_lints
description: Opinionated lints for Dart and Flutter projects.
version: 2.1.2
homepage: https://github.com/deminearchiver/dart-flutter-packages
repository: https://github.com/deminearchiver/dart-flutter-packages/tree/main/packages/deminearchiver_lints
issue_tracker: https://github.com/deminearchiver/dart-flutter-packages/issues
topics: [lints, analyzer, analysis]
resolution: workspace

environment:
  sdk: ^3.13.0
