name: deminearchiver_lints
description: Opinionated lints for Dart and Flutter projects.
version: 2.1.1
homepage: https://github.com/deminearchiver/dart-flutter-packages
repository: https://github.com/deminearchiver/dart-flutter-packages/tree/main/packages/deminearchiver_lints
issue_tracker: https://github.com/deminearchiver/dart-flutter-packages/issues
topics: [lints, analyzer, analysis]
resolution: workspace

environment:
  sdk: ^3.10.0

dependencies:
  flutter_lints: ^6.0.0
  lints: ^6.0.0
  very_good_analysis: ^10.0.0
