name: material
version: 2.0.0
homepage: https://github.com/deminearchiver/dart-flutter-packages
repository: https://github.com/deminearchiver/dart-flutter-packages/tree/main/packages/framework/material
issue_tracker: https://github.com/deminearchiver/dart-flutter-packages/issues
topics: [ui, widgets, material]
publish_to: none
resolution: workspace

environment:
  sdk: ^3.13.0
  flutter: ">=3.47.0"

dependencies:
  # SDK dependencies
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Path dependencies
  animation:
    path: ../animation
  layout:
    path: ../layout

  # Hosted dependencies
  collection: ^1.19.1
  cupertino_ui: ^1.0.0
  google_symbols_icons: ^0.1.0
  libmonet: 2.0.0-dev.20
  luminous_symbols_icons: ^0.1.0
  material_3p: 0.5.0
  material_symbols_icons: ^4.2960.0
  material_ui: ^1.0.0
  meta: ^1.18.0
  motor: ^1.1.0
  nested: ^1.0.0
  touch_targets: ^0.5.0

dev_dependencies:
  # SDK dependencies
  flutter_test:
    sdk: flutter

  # Hosted dependencies
  build_runner: ^2.15.0
  deminearchiver_lints: ^3.1.0
