// AUTO GENERATED BY JNIGEN 0.16.0. DO NOT EDIT!

// ignore_for_file: annotate_overrides
// ignore_for_file: argument_type_not_assignable
// ignore_for_file: camel_case_extensions
// ignore_for_file: camel_case_types
// ignore_for_file: constant_identifier_names
// ignore_for_file: comment_references
// ignore_for_file: doc_directive_unknown
// ignore_for_file: file_names
// ignore_for_file: inference_failure_on_untyped_parameter
// ignore_for_file: invalid_internal_annotation
// ignore_for_file: invalid_use_of_internal_member
// ignore_for_file: library_prefixes
// ignore_for_file: lines_longer_than_80_chars
// ignore_for_file: no_leading_underscores_for_library_prefixes
// ignore_for_file: no_leading_underscores_for_local_identifiers
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: only_throw_errors
// ignore_for_file: overridden_fields
// ignore_for_file: prefer_double_quotes
// ignore_for_file: unintended_html_in_doc_comment
// ignore_for_file: unnecessary_cast
// ignore_for_file: unnecessary_non_null_assertion
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: unused_element
// ignore_for_file: unused_field
// ignore_for_file: unused_import
// ignore_for_file: unused_local_variable
// ignore_for_file: unused_shown_name
// ignore_for_file: use_super_parameters

import 'dart:core' as core$_;
import 'dart:core' show Object, String;

import 'package:jni/_internal.dart' as jni$_;
import 'package:jni/jni.dart' as jni$_;

const _$jniVersionCheck = jni$_.JniVersionCheck(1, 0);

/// from: `dev.deminearchiver.screen_corners_ffi.ScreenCorners$Companion`
extension type ScreenCorners$Companion._(jni$_.JObject _$this)
    implements jni$_.JObject {
  static final _class = jni$_.JClass.forName(
    r'dev/deminearchiver/screen_corners_ffi/ScreenCorners$Companion',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<ScreenCorners$Companion> type =
      $ScreenCorners$Companion$Type$();
  static final _id_new$ = _class.constructorId(
    r'(Lkotlin/jvm/internal/DefaultConstructorMarker;)V',
  );

  static final _new$ =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `synthetic public void <init>(kotlin.jvm.internal.DefaultConstructorMarker defaultConstructorMarker)`
  /// The returned object must be released after use, by calling the [release] method.
  factory ScreenCorners$Companion(jni$_.JObject? defaultConstructorMarker) {
    final _$defaultConstructorMarker =
        defaultConstructorMarker?.reference ?? jni$_.jNullReference;
    return _new$(
      _class.reference.pointer,
      _id_new$.pointer,
      _$defaultConstructorMarker.pointer,
    ).object<ScreenCorners$Companion>();
  }
}

extension ScreenCorners$Companion$$Methods on ScreenCorners$Companion {
  static final _id_fromActivity = ScreenCorners$Companion._class.instanceMethodId(
    r'fromActivity',
    r'(Landroid/app/Activity;)Ldev/deminearchiver/screen_corners_ffi/ScreenCorners;',
  );

  static final _fromActivity =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public fun fromActivity(activity: android.app.Activity): dev.deminearchiver.screen_corners_ffi.ScreenCorners`
  /// The returned object must be released after use, by calling the [release] method.
  ScreenCorners fromActivity(jni$_.JObject activity) {
    final _$activity = activity.reference;
    return _fromActivity(
      reference.pointer,
      _id_fromActivity.pointer,
      _$activity.pointer,
    ).object<ScreenCorners>();
  }
}

final class $ScreenCorners$Companion$Type$
    extends jni$_.JType<ScreenCorners$Companion> {
  @jni$_.internal
  const $ScreenCorners$Companion$Type$();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Ldev/deminearchiver/screen_corners_ffi/ScreenCorners$Companion;';
}

/// from: `dev.deminearchiver.screen_corners_ffi.ScreenCorners`
extension type ScreenCorners._(jni$_.JObject _$this) implements jni$_.JObject {
  static final _class = jni$_.JClass.forName(
    r'dev/deminearchiver/screen_corners_ffi/ScreenCorners',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<ScreenCorners> type = $ScreenCorners$Type$();
  static final _id_Companion = _class.staticFieldId(
    r'Companion',
    r'Ldev/deminearchiver/screen_corners_ffi/ScreenCorners$Companion;',
  );

  /// from: `static public final dev.deminearchiver.screen_corners_ffi.ScreenCorners$Companion Companion`
  /// The returned object must be released after use, by calling the [release] method.
  static ScreenCorners$Companion get Companion =>
      _id_Companion.get(_class, ScreenCorners$Companion.type)
          as ScreenCorners$Companion;

  static final _id_new$ = _class.constructorId(
    r'(Ljava/lang/Double;Ljava/lang/Double;Ljava/lang/Double;Ljava/lang/Double;)V',
  );

  static final _new$ =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                  )
                >,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void <init>(java.lang.Double double, java.lang.Double double1, java.lang.Double double2, java.lang.Double double3)`
  /// The returned object must be released after use, by calling the [release] method.
  factory ScreenCorners(
    jni$_.JDouble? double,
    jni$_.JDouble? double1,
    jni$_.JDouble? double2,
    jni$_.JDouble? double3,
  ) {
    final _$double = double?.reference ?? jni$_.jNullReference;
    final _$double1 = double1?.reference ?? jni$_.jNullReference;
    final _$double2 = double2?.reference ?? jni$_.jNullReference;
    final _$double3 = double3?.reference ?? jni$_.jNullReference;
    return _new$(
      _class.reference.pointer,
      _id_new$.pointer,
      _$double.pointer,
      _$double1.pointer,
      _$double2.pointer,
      _$double3.pointer,
    ).object<ScreenCorners>();
  }

  static final _id_new$1 = _class.constructorId(
    r'(Ljava/lang/Double;Ljava/lang/Double;Ljava/lang/Double;Ljava/lang/Double;ILkotlin/jvm/internal/DefaultConstructorMarker;)V',
  );

  static final _new$1 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Int32,
                    jni$_.Pointer<jni$_.Void>,
                  )
                >,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              core$_.int,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `synthetic public void <init>(java.lang.Double double, java.lang.Double double1, java.lang.Double double2, java.lang.Double double3, int i, kotlin.jvm.internal.DefaultConstructorMarker defaultConstructorMarker)`
  /// The returned object must be released after use, by calling the [release] method.
  factory ScreenCorners.new$1(
    jni$_.JDouble? double,
    jni$_.JDouble? double1,
    jni$_.JDouble? double2,
    jni$_.JDouble? double3,
    core$_.int i,
    jni$_.JObject? defaultConstructorMarker,
  ) {
    final _$double = double?.reference ?? jni$_.jNullReference;
    final _$double1 = double1?.reference ?? jni$_.jNullReference;
    final _$double2 = double2?.reference ?? jni$_.jNullReference;
    final _$double3 = double3?.reference ?? jni$_.jNullReference;
    final _$defaultConstructorMarker =
        defaultConstructorMarker?.reference ?? jni$_.jNullReference;
    return _new$1(
      _class.reference.pointer,
      _id_new$1.pointer,
      _$double.pointer,
      _$double1.pointer,
      _$double2.pointer,
      _$double3.pointer,
      i,
      _$defaultConstructorMarker.pointer,
    ).object<ScreenCorners>();
  }

  static final _id_new$2 = _class.constructorId(r'()V');

  static final _new$2 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public void <init>()`
  /// The returned object must be released after use, by calling the [release] method.
  factory ScreenCorners.new$2() {
    return _new$2(
      _class.reference.pointer,
      _id_new$2.pointer,
    ).object<ScreenCorners>();
  }

  static final _id_fromActivity = _class.staticMethodId(
    r'fromActivity',
    r'(Landroid/app/Activity;)Ldev/deminearchiver/screen_corners_ffi/ScreenCorners;',
  );

  static final _fromActivity =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallStaticObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `static public final dev.deminearchiver.screen_corners_ffi.ScreenCorners fromActivity(android.app.Activity activity)`
  /// The returned object must be released after use, by calling the [release] method.
  static ScreenCorners fromActivity(jni$_.JObject activity) {
    final _$activity = activity.reference;
    return _fromActivity(
      _class.reference.pointer,
      _id_fromActivity.pointer,
      _$activity.pointer,
    ).object<ScreenCorners>();
  }
}

extension ScreenCorners$$Methods on ScreenCorners {
  static final _id_get$topLeft = ScreenCorners._class.instanceMethodId(
    r'getTopLeft',
    r'()Ljava/lang/Double;',
  );

  static final _get$topLeft =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public final java.lang.Double getTopLeft()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JDouble? get topLeft {
    return _get$topLeft(
      reference.pointer,
      _id_get$topLeft.pointer,
    ).object<jni$_.JDouble?>();
  }

  static final _id_get$topRight = ScreenCorners._class.instanceMethodId(
    r'getTopRight',
    r'()Ljava/lang/Double;',
  );

  static final _get$topRight =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public final java.lang.Double getTopRight()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JDouble? get topRight {
    return _get$topRight(
      reference.pointer,
      _id_get$topRight.pointer,
    ).object<jni$_.JDouble?>();
  }

  static final _id_get$bottomLeft = ScreenCorners._class.instanceMethodId(
    r'getBottomLeft',
    r'()Ljava/lang/Double;',
  );

  static final _get$bottomLeft =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public final java.lang.Double getBottomLeft()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JDouble? get bottomLeft {
    return _get$bottomLeft(
      reference.pointer,
      _id_get$bottomLeft.pointer,
    ).object<jni$_.JDouble?>();
  }

  static final _id_get$bottomRight = ScreenCorners._class.instanceMethodId(
    r'getBottomRight',
    r'()Ljava/lang/Double;',
  );

  static final _get$bottomRight =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public final java.lang.Double getBottomRight()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JDouble? get bottomRight {
    return _get$bottomRight(
      reference.pointer,
      _id_get$bottomRight.pointer,
    ).object<jni$_.JDouble?>();
  }

  static final _id_component1 = ScreenCorners._class.instanceMethodId(
    r'component1',
    r'()Ljava/lang/Double;',
  );

  static final _component1 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public operator fun component1(): kotlin.Double?`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JDouble? component1() {
    return _component1(
      reference.pointer,
      _id_component1.pointer,
    ).object<jni$_.JDouble?>();
  }

  static final _id_component2 = ScreenCorners._class.instanceMethodId(
    r'component2',
    r'()Ljava/lang/Double;',
  );

  static final _component2 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public operator fun component2(): kotlin.Double?`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JDouble? component2() {
    return _component2(
      reference.pointer,
      _id_component2.pointer,
    ).object<jni$_.JDouble?>();
  }

  static final _id_component3 = ScreenCorners._class.instanceMethodId(
    r'component3',
    r'()Ljava/lang/Double;',
  );

  static final _component3 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public operator fun component3(): kotlin.Double?`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JDouble? component3() {
    return _component3(
      reference.pointer,
      _id_component3.pointer,
    ).object<jni$_.JDouble?>();
  }

  static final _id_component4 = ScreenCorners._class.instanceMethodId(
    r'component4',
    r'()Ljava/lang/Double;',
  );

  static final _component4 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public operator fun component4(): kotlin.Double?`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JDouble? component4() {
    return _component4(
      reference.pointer,
      _id_component4.pointer,
    ).object<jni$_.JDouble?>();
  }

  static final _id_copy = ScreenCorners._class.instanceMethodId(
    r'copy',
    r'(Ljava/lang/Double;Ljava/lang/Double;Ljava/lang/Double;Ljava/lang/Double;)Ldev/deminearchiver/screen_corners_ffi/ScreenCorners;',
  );

  static final _copy =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                  )
                >,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public fun copy(topLeft: kotlin.Double?, topRight: kotlin.Double?, bottomLeft: kotlin.Double?, bottomRight: kotlin.Double?): dev.deminearchiver.screen_corners_ffi.ScreenCorners`
  /// The returned object must be released after use, by calling the [release] method.
  ScreenCorners copy(
    jni$_.JDouble? double,
    jni$_.JDouble? double1,
    jni$_.JDouble? double2,
    jni$_.JDouble? double3,
  ) {
    final _$double = double?.reference ?? jni$_.jNullReference;
    final _$double1 = double1?.reference ?? jni$_.jNullReference;
    final _$double2 = double2?.reference ?? jni$_.jNullReference;
    final _$double3 = double3?.reference ?? jni$_.jNullReference;
    return _copy(
      reference.pointer,
      _id_copy.pointer,
      _$double.pointer,
      _$double1.pointer,
      _$double2.pointer,
      _$double3.pointer,
    ).object<ScreenCorners>();
  }

  static final _id_toString$1 = ScreenCorners._class.instanceMethodId(
    r'toString',
    r'()Ljava/lang/String;',
  );

  static final _toString$1 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public fun toString(): kotlin.String`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JString toString$1() {
    return _toString$1(
      reference.pointer,
      _id_toString$1.pointer,
    ).object<jni$_.JString>();
  }

  static final _id_hashCode$1 = ScreenCorners._class.instanceMethodId(
    r'hashCode',
    r'()I',
  );

  static final _hashCode$1 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallIntMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public fun hashCode(): kotlin.Int`
  core$_.int hashCode$1() {
    return _hashCode$1(reference.pointer, _id_hashCode$1.pointer).integer;
  }

  static final _id_equals = ScreenCorners._class.instanceMethodId(
    r'equals',
    r'(Ljava/lang/Object;)Z',
  );

  static final _equals =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallBooleanMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public operator fun equals(other: kotlin.Any?): kotlin.Boolean`
  core$_.bool equals(jni$_.JObject? object) {
    final _$object = object?.reference ?? jni$_.jNullReference;
    return _equals(
      reference.pointer,
      _id_equals.pointer,
      _$object.pointer,
    ).boolean;
  }
}

final class $ScreenCorners$Type$ extends jni$_.JType<ScreenCorners> {
  @jni$_.internal
  const $ScreenCorners$Type$();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Ldev/deminearchiver/screen_corners_ffi/ScreenCorners;';
}
