name: material_3p
description: 3P (third-party) version of the Material 3 Expressive package.
version: 0.5.0
homepage: https://github.com/deminearchiver/dart-flutter-packages
repository: https://github.com/deminearchiver/dart-flutter-packages/tree/main/packages/material_3p
issue_tracker: https://github.com/deminearchiver/dart-flutter-packages/issues
topics: [ui, widgets, material]
resolution: workspace

environment:
  sdk: ^3.13.0
  flutter: ">=3.47.0"

dependencies:
  # SDK dependencies
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Hosted dependencies
  androidx_graphics_shapes: ^1.7.0
  collection: ^1.19.1
  libmonet: ^2.0.0-dev.20
  material_symbols_icons: ^4.2960.0
  material_ui: ^1.0.0
  meta: ^1.19.0
  vector_math: ^2.4.2

dev_dependencies:
  # SDK dependencies
  flutter_test:
    sdk: flutter

  # Hosted dependencies
  deminearchiver_lints: ^3.0.1
  build_runner: ^2.15.0
