name: google_symbols_icons
description: Guard package for the Google Symbols icons generator.
version: 0.0.1
homepage: https://github.com/deminearchiver/dart-flutter-packages
repository: https://github.com/deminearchiver/dart-flutter-packages/tree/main/packages/google_symbols_icons
issue_tracker: https://github.com/deminearchiver/dart-flutter-packages/issues
resolution: workspace

environment:
  sdk: ^3.11.0
  flutter: ">=3.41.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  args: ^2.7.0
  deminearchiver_lints: ^2.1.2
  google_symbols: any

flutter:
  # fonts:
  # TODO: comment out after subsetting
  # - family: Google Symbols
  #   fonts:
  #     - asset: lib/fonts/GoogleSymbols.ttf
  # TODO: uncomment after subsetting
  # - family: Google Symbols Outlined
  #   fonts:
  #    - asset: lib/fonts/GoogleSymbolsOutlined.ttf
  # - family: Google Symbols Rounded
  #   fonts:
  #    - asset: lib/fonts/GoogleSymbolsRounded.ttf
  # - family: Google Symbols Sharp
  #   fonts:
  #    - asset: lib/fonts/GoogleSymbolsSharp.ttf
