name: package_info_ffi
description: An FFI-based version of the package_info_plus plugin.
version: 2.0.0
homepage: https://github.com/deminearchiver/dart-flutter-packages
repository: https://github.com/deminearchiver/dart-flutter-packages/tree/main/packages/package_info_ffi
issue_tracker: https://github.com/deminearchiver/dart-flutter-packages/issues
resolution: workspace

environment:
  sdk: ^3.11.0
  flutter: ">=3.41.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  clock: ^1.1.2
  ffi: ^2.2.0
  file: ^7.0.1
  http: ^1.6.0
  jni: ^1.0.0
  jni_flutter: ^1.0.1
  meta: ^1.17.0
  path: ^1.9.1
  plugin_platform_interface: ^2.1.8
  web: ^1.1.1
  win32: ^6.0.0
  win32_registry: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  deminearchiver_lints: ^3.1.0
  jnigen: ^0.16.0

flutter:
  plugin:
    platforms:
      android:
        dartPluginClass: PackageInfoAndroid
        ffiPlugin: true
      linux:
        dartPluginClass: PackageInfoLinux
      windows:
        dartPluginClass: PackageInfoWindows
