// AUTO GENERATED BY JNIGEN 0.15.0. DO NOT EDIT!

// ignore_for_file: annotate_overrides
// ignore_for_file: argument_type_not_assignable
// ignore_for_file: camel_case_extensions
// ignore_for_file: camel_case_types
// ignore_for_file: constant_identifier_names
// ignore_for_file: comment_references
// ignore_for_file: doc_directive_unknown
// ignore_for_file: file_names
// ignore_for_file: inference_failure_on_untyped_parameter
// ignore_for_file: invalid_internal_annotation
// ignore_for_file: invalid_use_of_internal_member
// ignore_for_file: library_prefixes
// ignore_for_file: lines_longer_than_80_chars
// ignore_for_file: no_leading_underscores_for_library_prefixes
// ignore_for_file: no_leading_underscores_for_local_identifiers
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: only_throw_errors
// ignore_for_file: overridden_fields
// ignore_for_file: prefer_double_quotes
// ignore_for_file: unintended_html_in_doc_comment
// ignore_for_file: unnecessary_cast
// ignore_for_file: unnecessary_non_null_assertion
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: unused_element
// ignore_for_file: unused_field
// ignore_for_file: unused_import
// ignore_for_file: unused_local_variable
// ignore_for_file: unused_shown_name
// ignore_for_file: use_super_parameters

import 'dart:core' as core$_;
import 'dart:core' show Object, String, bool, double, int;

import 'package:jni/_internal.dart' as jni$_;
import 'package:jni/jni.dart' as jni$_;

/// from: `dev.deminearchiver.embedded_photo_picker.EmbeddedPhotoPickerPlugin`
class EmbeddedPhotoPickerPlugin extends jni$_.JObject {
  @jni$_.internal
  @core$_.override
  final jni$_.JType<EmbeddedPhotoPickerPlugin> $type;

  @jni$_.internal
  EmbeddedPhotoPickerPlugin.fromReference(jni$_.JReference reference)
    : $type = type,
      super.fromReference(reference);

  static final _class = jni$_.JClass.forName(
    r'dev/deminearchiver/embedded_photo_picker/EmbeddedPhotoPickerPlugin',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<EmbeddedPhotoPickerPlugin?> nullableType =
      $EmbeddedPhotoPickerPlugin$NullableType$();

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<EmbeddedPhotoPickerPlugin> type =
      $EmbeddedPhotoPickerPlugin$Type$();
  static final _id_new$ = _class.constructorId(r'()V');

  static final _new$ =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public void <init>()`
  /// The returned object must be released after use, by calling the [release] method.
  factory EmbeddedPhotoPickerPlugin() {
    return EmbeddedPhotoPickerPlugin.fromReference(
      _new$(_class.reference.pointer, _id_new$ as jni$_.JMethodIDPtr).reference,
    );
  }

  static final _id_onAttachedToEngine = _class.instanceMethodId(
    r'onAttachedToEngine',
    r'(Lio/flutter/embedding/engine/plugins/FlutterPlugin$FlutterPluginBinding;)V',
  );

  static final _onAttachedToEngine =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public fun onAttachedToEngine(flutterPluginBinding: io.flutter.embedding.engine.plugins.FlutterPlugin.FlutterPluginBinding): kotlin.Unit`
  void onAttachedToEngine(jni$_.JObject flutterPluginBinding) {
    final _$flutterPluginBinding = flutterPluginBinding.reference;
    _onAttachedToEngine(
      reference.pointer,
      _id_onAttachedToEngine as jni$_.JMethodIDPtr,
      _$flutterPluginBinding.pointer,
    ).check();
  }

  static final _id_onMethodCall = _class.instanceMethodId(
    r'onMethodCall',
    r'(Lio/flutter/plugin/common/MethodCall;Lio/flutter/plugin/common/MethodChannel$Result;)V',
  );

  static final _onMethodCall =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (jni$_.Pointer<jni$_.Void>, jni$_.Pointer<jni$_.Void>)
                >,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public fun onMethodCall(call: io.flutter.plugin.common.MethodCall, result: io.flutter.plugin.common.MethodChannel.Result): kotlin.Unit`
  void onMethodCall(jni$_.JObject methodCall, jni$_.JObject result) {
    final _$methodCall = methodCall.reference;
    final _$result = result.reference;
    _onMethodCall(
      reference.pointer,
      _id_onMethodCall as jni$_.JMethodIDPtr,
      _$methodCall.pointer,
      _$result.pointer,
    ).check();
  }

  static final _id_onDetachedFromEngine = _class.instanceMethodId(
    r'onDetachedFromEngine',
    r'(Lio/flutter/embedding/engine/plugins/FlutterPlugin$FlutterPluginBinding;)V',
  );

  static final _onDetachedFromEngine =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public fun onDetachedFromEngine(binding: io.flutter.embedding.engine.plugins.FlutterPlugin.FlutterPluginBinding): kotlin.Unit`
  void onDetachedFromEngine(jni$_.JObject flutterPluginBinding) {
    final _$flutterPluginBinding = flutterPluginBinding.reference;
    _onDetachedFromEngine(
      reference.pointer,
      _id_onDetachedFromEngine as jni$_.JMethodIDPtr,
      _$flutterPluginBinding.pointer,
    ).check();
  }
}

final class $EmbeddedPhotoPickerPlugin$NullableType$
    extends jni$_.JType<EmbeddedPhotoPickerPlugin?> {
  @jni$_.internal
  const $EmbeddedPhotoPickerPlugin$NullableType$();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Ldev/deminearchiver/embedded_photo_picker/EmbeddedPhotoPickerPlugin;';

  @jni$_.internal
  @core$_.override
  EmbeddedPhotoPickerPlugin? fromReference(jni$_.JReference reference) =>
      reference.isNull
      ? null
      : EmbeddedPhotoPickerPlugin.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$NullableType$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<EmbeddedPhotoPickerPlugin?> get nullableType => this;

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($EmbeddedPhotoPickerPlugin$NullableType$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($EmbeddedPhotoPickerPlugin$NullableType$) &&
        other is $EmbeddedPhotoPickerPlugin$NullableType$;
  }
}

final class $EmbeddedPhotoPickerPlugin$Type$
    extends jni$_.JType<EmbeddedPhotoPickerPlugin> {
  @jni$_.internal
  const $EmbeddedPhotoPickerPlugin$Type$();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Ldev/deminearchiver/embedded_photo_picker/EmbeddedPhotoPickerPlugin;';

  @jni$_.internal
  @core$_.override
  EmbeddedPhotoPickerPlugin fromReference(jni$_.JReference reference) =>
      EmbeddedPhotoPickerPlugin.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$NullableType$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<EmbeddedPhotoPickerPlugin?> get nullableType =>
      const $EmbeddedPhotoPickerPlugin$NullableType$();

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($EmbeddedPhotoPickerPlugin$Type$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($EmbeddedPhotoPickerPlugin$Type$) &&
        other is $EmbeddedPhotoPickerPlugin$Type$;
  }
}
