// AUTO GENERATED BY JNIGEN 0.16.0. DO NOT EDIT!

// ignore_for_file: annotate_overrides
// ignore_for_file: argument_type_not_assignable
// ignore_for_file: camel_case_extensions
// ignore_for_file: camel_case_types
// ignore_for_file: constant_identifier_names
// ignore_for_file: comment_references
// ignore_for_file: doc_directive_unknown
// ignore_for_file: file_names
// ignore_for_file: inference_failure_on_untyped_parameter
// ignore_for_file: invalid_internal_annotation
// ignore_for_file: invalid_use_of_internal_member
// ignore_for_file: library_prefixes
// ignore_for_file: lines_longer_than_80_chars
// ignore_for_file: no_leading_underscores_for_library_prefixes
// ignore_for_file: no_leading_underscores_for_local_identifiers
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: only_throw_errors
// ignore_for_file: overridden_fields
// ignore_for_file: prefer_double_quotes
// ignore_for_file: unintended_html_in_doc_comment
// ignore_for_file: unnecessary_cast
// ignore_for_file: unnecessary_non_null_assertion
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: unused_element
// ignore_for_file: unused_field
// ignore_for_file: unused_import
// ignore_for_file: unused_local_variable
// ignore_for_file: unused_shown_name
// ignore_for_file: use_super_parameters

import 'dart:core' as core$_;
import 'dart:core' show Object, String;

import 'package:jni/_internal.dart' as jni$_;
import 'package:jni/jni.dart' as jni$_;

const _$jniVersionCheck = jni$_.JniVersionCheck(1, 0);

/// from: `dev.deminearchiver.device_info_ffi.DeviceInfo$BuildVersion`
extension type DeviceInfo$BuildVersion._(jni$_.JObject _$this)
    implements jni$_.JObject {
  static final _class = jni$_.JClass.forName(
    r'dev/deminearchiver/device_info_ffi/DeviceInfo$BuildVersion',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<DeviceInfo$BuildVersion> type =
      $DeviceInfo$BuildVersion$Type$();
  static final _id_new$ = _class.constructorId(
    r'(Ljava/lang/String;Ljava/lang/Integer;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;I)V',
  );

  static final _new$ =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Int32,
                  )
                >,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              core$_.int,
            )
          >();

  /// from: `public void <init>(java.lang.String string, java.lang.Integer integer, java.lang.String string1, java.lang.String string2, java.lang.String string3, java.lang.String string4, int i)`
  /// The returned object must be released after use, by calling the [release] method.
  factory DeviceInfo$BuildVersion(
    jni$_.JString? string,
    jni$_.JInteger? integer,
    jni$_.JString? string1,
    jni$_.JString string2,
    jni$_.JString string3,
    jni$_.JString string4,
    core$_.int i,
  ) {
    final _$string = string?.reference ?? jni$_.jNullReference;
    final _$integer = integer?.reference ?? jni$_.jNullReference;
    final _$string1 = string1?.reference ?? jni$_.jNullReference;
    final _$string2 = string2.reference;
    final _$string3 = string3.reference;
    final _$string4 = string4.reference;
    return _new$(
      _class.reference.pointer,
      _id_new$.pointer,
      _$string.pointer,
      _$integer.pointer,
      _$string1.pointer,
      _$string2.pointer,
      _$string3.pointer,
      _$string4.pointer,
      i,
    ).object<DeviceInfo$BuildVersion>();
  }
}

extension DeviceInfo$BuildVersion$$Methods on DeviceInfo$BuildVersion {
  static final _id_get$baseOS = DeviceInfo$BuildVersion._class.instanceMethodId(
    r'getBaseOS',
    r'()Ljava/lang/String;',
  );

  static final _get$baseOS =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public final java.lang.String getBaseOS()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JString? get baseOS {
    return _get$baseOS(
      reference.pointer,
      _id_get$baseOS.pointer,
    ).object<jni$_.JString?>();
  }

  static final _id_get$previewSdkInt = DeviceInfo$BuildVersion._class
      .instanceMethodId(r'getPreviewSdkInt', r'()Ljava/lang/Integer;');

  static final _get$previewSdkInt =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public final java.lang.Integer getPreviewSdkInt()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JInteger? get previewSdkInt {
    return _get$previewSdkInt(
      reference.pointer,
      _id_get$previewSdkInt.pointer,
    ).object<jni$_.JInteger?>();
  }

  static final _id_get$securityPatch = DeviceInfo$BuildVersion._class
      .instanceMethodId(r'getSecurityPatch', r'()Ljava/lang/String;');

  static final _get$securityPatch =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public final java.lang.String getSecurityPatch()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JString? get securityPatch {
    return _get$securityPatch(
      reference.pointer,
      _id_get$securityPatch.pointer,
    ).object<jni$_.JString?>();
  }

  static final _id_get$codename = DeviceInfo$BuildVersion._class
      .instanceMethodId(r'getCodename', r'()Ljava/lang/String;');

  static final _get$codename =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public final java.lang.String getCodename()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JString get codename {
    return _get$codename(
      reference.pointer,
      _id_get$codename.pointer,
    ).object<jni$_.JString>();
  }

  static final _id_get$incremental = DeviceInfo$BuildVersion._class
      .instanceMethodId(r'getIncremental', r'()Ljava/lang/String;');

  static final _get$incremental =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public final java.lang.String getIncremental()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JString get incremental {
    return _get$incremental(
      reference.pointer,
      _id_get$incremental.pointer,
    ).object<jni$_.JString>();
  }

  static final _id_get$release$1 = DeviceInfo$BuildVersion._class
      .instanceMethodId(r'getRelease', r'()Ljava/lang/String;');

  static final _get$release$1 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public final java.lang.String getRelease()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JString get release$1 {
    return _get$release$1(
      reference.pointer,
      _id_get$release$1.pointer,
    ).object<jni$_.JString>();
  }

  static final _id_get$sdkInt = DeviceInfo$BuildVersion._class.instanceMethodId(
    r'getSdkInt',
    r'()I',
  );

  static final _get$sdkInt =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallIntMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public final int getSdkInt()`
  core$_.int get sdkInt {
    return _get$sdkInt(reference.pointer, _id_get$sdkInt.pointer).integer;
  }
}

final class $DeviceInfo$BuildVersion$Type$
    extends jni$_.JType<DeviceInfo$BuildVersion> {
  @jni$_.internal
  const $DeviceInfo$BuildVersion$Type$();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Ldev/deminearchiver/device_info_ffi/DeviceInfo$BuildVersion;';
}

/// from: `dev.deminearchiver.device_info_ffi.DeviceInfo`
extension type DeviceInfo._(jni$_.JObject _$this) implements jni$_.JObject {
  static final _class = jni$_.JClass.forName(
    r'dev/deminearchiver/device_info_ffi/DeviceInfo',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<DeviceInfo> type = $DeviceInfo$Type$();
  static final _id_new$ = _class.constructorId(
    r'(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/util/List;Ljava/util/List;Ljava/util/List;Ljava/lang/String;Ljava/lang/String;ZLjava/util/List;JJLdev/deminearchiver/device_info_ffi/DeviceInfo$BuildVersion;ZJJ)V',
  );

  static final _new$ =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Int32,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Int64,
                    jni$_.Int64,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Int32,
                    jni$_.Int64,
                    jni$_.Int64,
                  )
                >,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              core$_.int,
              jni$_.Pointer<jni$_.Void>,
              core$_.int,
              core$_.int,
              jni$_.Pointer<jni$_.Void>,
              core$_.int,
              core$_.int,
              core$_.int,
            )
          >();

  /// from: `public void <init>(java.lang.String string, java.lang.String string1, java.lang.String string2, java.lang.String string3, java.lang.String string4, java.lang.String string5, java.lang.String string6, java.lang.String string7, java.lang.String string8, java.lang.String string9, java.lang.String string10, java.lang.String string11, java.lang.String string12, java.util.List<java.lang.String> list, java.util.List<java.lang.String> list1, java.util.List<java.lang.String> list2, java.lang.String string13, java.lang.String string14, boolean z, java.util.List<java.lang.String> list3, long j, long j1, dev.deminearchiver.device_info_ffi.DeviceInfo$BuildVersion buildVersion, boolean z1, long j2, long j3)`
  /// The returned object must be released after use, by calling the [release] method.
  factory DeviceInfo(
    jni$_.JString string,
    jni$_.JString string1,
    jni$_.JString string2,
    jni$_.JString string3,
    jni$_.JString string4,
    jni$_.JString string5,
    jni$_.JString string6,
    jni$_.JString string7,
    jni$_.JString string8,
    jni$_.JString string9,
    jni$_.JString string10,
    jni$_.JString string11,
    jni$_.JString? string12,
    jni$_.JList<jni$_.JString>? list,
    jni$_.JList<jni$_.JString>? list1,
    jni$_.JList<jni$_.JString>? list2,
    jni$_.JString string13,
    jni$_.JString string14,
    core$_.bool z,
    jni$_.JList<jni$_.JString> list3,
    core$_.int j,
    core$_.int j1,
    DeviceInfo$BuildVersion buildVersion,
    core$_.bool z1,
    core$_.int j2,
    core$_.int j3,
  ) {
    final _$string = string.reference;
    final _$string1 = string1.reference;
    final _$string2 = string2.reference;
    final _$string3 = string3.reference;
    final _$string4 = string4.reference;
    final _$string5 = string5.reference;
    final _$string6 = string6.reference;
    final _$string7 = string7.reference;
    final _$string8 = string8.reference;
    final _$string9 = string9.reference;
    final _$string10 = string10.reference;
    final _$string11 = string11.reference;
    final _$string12 = string12?.reference ?? jni$_.jNullReference;
    final _$list = list?.reference ?? jni$_.jNullReference;
    final _$list1 = list1?.reference ?? jni$_.jNullReference;
    final _$list2 = list2?.reference ?? jni$_.jNullReference;
    final _$string13 = string13.reference;
    final _$string14 = string14.reference;
    final _$list3 = list3.reference;
    final _$buildVersion = buildVersion.reference;
    return _new$(
      _class.reference.pointer,
      _id_new$.pointer,
      _$string.pointer,
      _$string1.pointer,
      _$string2.pointer,
      _$string3.pointer,
      _$string4.pointer,
      _$string5.pointer,
      _$string6.pointer,
      _$string7.pointer,
      _$string8.pointer,
      _$string9.pointer,
      _$string10.pointer,
      _$string11.pointer,
      _$string12.pointer,
      _$list.pointer,
      _$list1.pointer,
      _$list2.pointer,
      _$string13.pointer,
      _$string14.pointer,
      z ? 1 : 0,
      _$list3.pointer,
      j,
      j1,
      _$buildVersion.pointer,
      z1 ? 1 : 0,
      j2,
      j3,
    ).object<DeviceInfo>();
  }
}

extension DeviceInfo$$Methods on DeviceInfo {
  static final _id_get$board = DeviceInfo._class.instanceMethodId(
    r'getBoard',
    r'()Ljava/lang/String;',
  );

  static final _get$board =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public final java.lang.String getBoard()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JString get board {
    return _get$board(
      reference.pointer,
      _id_get$board.pointer,
    ).object<jni$_.JString>();
  }

  static final _id_get$bootloader = DeviceInfo._class.instanceMethodId(
    r'getBootloader',
    r'()Ljava/lang/String;',
  );

  static final _get$bootloader =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public final java.lang.String getBootloader()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JString get bootloader {
    return _get$bootloader(
      reference.pointer,
      _id_get$bootloader.pointer,
    ).object<jni$_.JString>();
  }

  static final _id_get$brand = DeviceInfo._class.instanceMethodId(
    r'getBrand',
    r'()Ljava/lang/String;',
  );

  static final _get$brand =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public final java.lang.String getBrand()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JString get brand {
    return _get$brand(
      reference.pointer,
      _id_get$brand.pointer,
    ).object<jni$_.JString>();
  }

  static final _id_get$device = DeviceInfo._class.instanceMethodId(
    r'getDevice',
    r'()Ljava/lang/String;',
  );

  static final _get$device =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public final java.lang.String getDevice()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JString get device {
    return _get$device(
      reference.pointer,
      _id_get$device.pointer,
    ).object<jni$_.JString>();
  }

  static final _id_get$display = DeviceInfo._class.instanceMethodId(
    r'getDisplay',
    r'()Ljava/lang/String;',
  );

  static final _get$display =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public final java.lang.String getDisplay()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JString get display {
    return _get$display(
      reference.pointer,
      _id_get$display.pointer,
    ).object<jni$_.JString>();
  }

  static final _id_get$fingerprint = DeviceInfo._class.instanceMethodId(
    r'getFingerprint',
    r'()Ljava/lang/String;',
  );

  static final _get$fingerprint =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public final java.lang.String getFingerprint()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JString get fingerprint {
    return _get$fingerprint(
      reference.pointer,
      _id_get$fingerprint.pointer,
    ).object<jni$_.JString>();
  }

  static final _id_get$hardware = DeviceInfo._class.instanceMethodId(
    r'getHardware',
    r'()Ljava/lang/String;',
  );

  static final _get$hardware =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public final java.lang.String getHardware()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JString get hardware {
    return _get$hardware(
      reference.pointer,
      _id_get$hardware.pointer,
    ).object<jni$_.JString>();
  }

  static final _id_get$host = DeviceInfo._class.instanceMethodId(
    r'getHost',
    r'()Ljava/lang/String;',
  );

  static final _get$host =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public final java.lang.String getHost()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JString get host {
    return _get$host(
      reference.pointer,
      _id_get$host.pointer,
    ).object<jni$_.JString>();
  }

  static final _id_get$id = DeviceInfo._class.instanceMethodId(
    r'getId',
    r'()Ljava/lang/String;',
  );

  static final _get$id =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public final java.lang.String getId()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JString get id {
    return _get$id(
      reference.pointer,
      _id_get$id.pointer,
    ).object<jni$_.JString>();
  }

  static final _id_get$manufacturer = DeviceInfo._class.instanceMethodId(
    r'getManufacturer',
    r'()Ljava/lang/String;',
  );

  static final _get$manufacturer =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public final java.lang.String getManufacturer()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JString get manufacturer {
    return _get$manufacturer(
      reference.pointer,
      _id_get$manufacturer.pointer,
    ).object<jni$_.JString>();
  }

  static final _id_get$model = DeviceInfo._class.instanceMethodId(
    r'getModel',
    r'()Ljava/lang/String;',
  );

  static final _get$model =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public final java.lang.String getModel()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JString get model {
    return _get$model(
      reference.pointer,
      _id_get$model.pointer,
    ).object<jni$_.JString>();
  }

  static final _id_get$product = DeviceInfo._class.instanceMethodId(
    r'getProduct',
    r'()Ljava/lang/String;',
  );

  static final _get$product =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public final java.lang.String getProduct()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JString get product {
    return _get$product(
      reference.pointer,
      _id_get$product.pointer,
    ).object<jni$_.JString>();
  }

  static final _id_get$name = DeviceInfo._class.instanceMethodId(
    r'getName',
    r'()Ljava/lang/String;',
  );

  static final _get$name =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public final java.lang.String getName()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JString? get name {
    return _get$name(
      reference.pointer,
      _id_get$name.pointer,
    ).object<jni$_.JString?>();
  }

  static final _id_get$supported32BitAbis = DeviceInfo._class.instanceMethodId(
    r'getSupported32BitAbis',
    r'()Ljava/util/List;',
  );

  static final _get$supported32BitAbis =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public final java.util.List<java.lang.String> getSupported32BitAbis()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JList<jni$_.JString>? get supported32BitAbis {
    return _get$supported32BitAbis(
      reference.pointer,
      _id_get$supported32BitAbis.pointer,
    ).object<jni$_.JList<jni$_.JString>?>();
  }

  static final _id_get$supported64BitAbis = DeviceInfo._class.instanceMethodId(
    r'getSupported64BitAbis',
    r'()Ljava/util/List;',
  );

  static final _get$supported64BitAbis =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public final java.util.List<java.lang.String> getSupported64BitAbis()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JList<jni$_.JString>? get supported64BitAbis {
    return _get$supported64BitAbis(
      reference.pointer,
      _id_get$supported64BitAbis.pointer,
    ).object<jni$_.JList<jni$_.JString>?>();
  }

  static final _id_get$supportedAbis = DeviceInfo._class.instanceMethodId(
    r'getSupportedAbis',
    r'()Ljava/util/List;',
  );

  static final _get$supportedAbis =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public final java.util.List<java.lang.String> getSupportedAbis()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JList<jni$_.JString>? get supportedAbis {
    return _get$supportedAbis(
      reference.pointer,
      _id_get$supportedAbis.pointer,
    ).object<jni$_.JList<jni$_.JString>?>();
  }

  static final _id_get$tags = DeviceInfo._class.instanceMethodId(
    r'getTags',
    r'()Ljava/lang/String;',
  );

  static final _get$tags =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public final java.lang.String getTags()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JString get tags {
    return _get$tags(
      reference.pointer,
      _id_get$tags.pointer,
    ).object<jni$_.JString>();
  }

  static final _id_get$type$1 = DeviceInfo._class.instanceMethodId(
    r'getType',
    r'()Ljava/lang/String;',
  );

  static final _get$type$1 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public final java.lang.String getType()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JString get type$1 {
    return _get$type$1(
      reference.pointer,
      _id_get$type$1.pointer,
    ).object<jni$_.JString>();
  }

  static final _id_get$isPhysicalDevice = DeviceInfo._class.instanceMethodId(
    r'isPhysicalDevice',
    r'()Z',
  );

  static final _get$isPhysicalDevice =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallBooleanMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public final boolean isPhysicalDevice()`
  core$_.bool get isPhysicalDevice {
    return _get$isPhysicalDevice(
      reference.pointer,
      _id_get$isPhysicalDevice.pointer,
    ).boolean;
  }

  static final _id_get$systemFeatures = DeviceInfo._class.instanceMethodId(
    r'getSystemFeatures',
    r'()Ljava/util/List;',
  );

  static final _get$systemFeatures =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public final java.util.List<java.lang.String> getSystemFeatures()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JList<jni$_.JString> get systemFeatures {
    return _get$systemFeatures(
      reference.pointer,
      _id_get$systemFeatures.pointer,
    ).object<jni$_.JList<jni$_.JString>>();
  }

  static final _id_get$freeDiskSize = DeviceInfo._class.instanceMethodId(
    r'getFreeDiskSize',
    r'()J',
  );

  static final _get$freeDiskSize =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallLongMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public final long getFreeDiskSize()`
  core$_.int get freeDiskSize {
    return _get$freeDiskSize(
      reference.pointer,
      _id_get$freeDiskSize.pointer,
    ).long;
  }

  static final _id_get$totalDiskSize = DeviceInfo._class.instanceMethodId(
    r'getTotalDiskSize',
    r'()J',
  );

  static final _get$totalDiskSize =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallLongMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public final long getTotalDiskSize()`
  core$_.int get totalDiskSize {
    return _get$totalDiskSize(
      reference.pointer,
      _id_get$totalDiskSize.pointer,
    ).long;
  }

  static final _id_get$version = DeviceInfo._class.instanceMethodId(
    r'getVersion',
    r'()Ldev/deminearchiver/device_info_ffi/DeviceInfo$BuildVersion;',
  );

  static final _get$version =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public final dev.deminearchiver.device_info_ffi.DeviceInfo$BuildVersion getVersion()`
  /// The returned object must be released after use, by calling the [release] method.
  DeviceInfo$BuildVersion get version {
    return _get$version(
      reference.pointer,
      _id_get$version.pointer,
    ).object<DeviceInfo$BuildVersion>();
  }

  static final _id_get$isLowRamDevice = DeviceInfo._class.instanceMethodId(
    r'isLowRamDevice',
    r'()Z',
  );

  static final _get$isLowRamDevice =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallBooleanMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public final boolean isLowRamDevice()`
  core$_.bool get isLowRamDevice {
    return _get$isLowRamDevice(
      reference.pointer,
      _id_get$isLowRamDevice.pointer,
    ).boolean;
  }

  static final _id_get$physicalRamSize = DeviceInfo._class.instanceMethodId(
    r'getPhysicalRamSize',
    r'()J',
  );

  static final _get$physicalRamSize =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallLongMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public final long getPhysicalRamSize()`
  core$_.int get physicalRamSize {
    return _get$physicalRamSize(
      reference.pointer,
      _id_get$physicalRamSize.pointer,
    ).long;
  }

  static final _id_get$availableRamSize = DeviceInfo._class.instanceMethodId(
    r'getAvailableRamSize',
    r'()J',
  );

  static final _get$availableRamSize =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallLongMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public final long getAvailableRamSize()`
  core$_.int get availableRamSize {
    return _get$availableRamSize(
      reference.pointer,
      _id_get$availableRamSize.pointer,
    ).long;
  }
}

final class $DeviceInfo$Type$ extends jni$_.JType<DeviceInfo> {
  @jni$_.internal
  const $DeviceInfo$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Ldev/deminearchiver/device_info_ffi/DeviceInfo;';
}

/// from: `dev.deminearchiver.device_info_ffi.DeviceInfoPlugin`
extension type DeviceInfoPlugin._(jni$_.JObject _$this)
    implements jni$_.JObject {
  static final _class = jni$_.JClass.forName(
    r'dev/deminearchiver/device_info_ffi/DeviceInfoPlugin',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<DeviceInfoPlugin> type = $DeviceInfoPlugin$Type$();
  static final _id_INSTANCE = _class.staticFieldId(
    r'INSTANCE',
    r'Ldev/deminearchiver/device_info_ffi/DeviceInfoPlugin;',
  );

  /// from: `static public final dev.deminearchiver.device_info_ffi.DeviceInfoPlugin INSTANCE`
  /// The returned object must be released after use, by calling the [release] method.
  static DeviceInfoPlugin get INSTANCE =>
      _id_INSTANCE.get(_class, DeviceInfoPlugin.type) as DeviceInfoPlugin;

  static final _id_getDeviceInfo = _class.staticMethodId(
    r'getDeviceInfo',
    r'(Landroid/content/Context;)Ldev/deminearchiver/device_info_ffi/DeviceInfo;',
  );

  static final _getDeviceInfo =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallStaticObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public fun getDeviceInfo(context: android.content.Context): dev.deminearchiver.device_info_ffi.DeviceInfo`
  /// The returned object must be released after use, by calling the [release] method.
  static DeviceInfo getDeviceInfo(jni$_.JObject context) {
    final _$context = context.reference;
    return _getDeviceInfo(
      _class.reference.pointer,
      _id_getDeviceInfo.pointer,
      _$context.pointer,
    ).object<DeviceInfo>();
  }
}

final class $DeviceInfoPlugin$Type$ extends jni$_.JType<DeviceInfoPlugin> {
  @jni$_.internal
  const $DeviceInfoPlugin$Type$();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Ldev/deminearchiver/device_info_ffi/DeviceInfoPlugin;';
}
