// AUTO GENERATED BY JNIGEN 0.15.0. DO NOT EDIT!

// ignore_for_file: annotate_overrides
// ignore_for_file: argument_type_not_assignable
// ignore_for_file: camel_case_extensions
// ignore_for_file: camel_case_types
// ignore_for_file: constant_identifier_names
// ignore_for_file: comment_references
// ignore_for_file: doc_directive_unknown
// ignore_for_file: file_names
// ignore_for_file: inference_failure_on_untyped_parameter
// ignore_for_file: invalid_internal_annotation
// ignore_for_file: invalid_use_of_internal_member
// ignore_for_file: library_prefixes
// ignore_for_file: lines_longer_than_80_chars
// ignore_for_file: no_leading_underscores_for_library_prefixes
// ignore_for_file: no_leading_underscores_for_local_identifiers
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: only_throw_errors
// ignore_for_file: overridden_fields
// ignore_for_file: prefer_double_quotes
// ignore_for_file: unintended_html_in_doc_comment
// ignore_for_file: unnecessary_cast
// ignore_for_file: unnecessary_non_null_assertion
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: unused_element
// ignore_for_file: unused_field
// ignore_for_file: unused_import
// ignore_for_file: unused_local_variable
// ignore_for_file: unused_shown_name
// ignore_for_file: use_super_parameters

import 'dart:core' as core$_;
import 'dart:core' show Object, String, bool, double, int;

import 'package:jni/_internal.dart' as jni$_;
import 'package:jni/jni.dart' as jni$_;

/// from: `io.github.deminearchiver.system_colors_android.SystemColorsPlugin`
class SystemColorsPlugin extends jni$_.JObject {
  @jni$_.internal
  @core$_.override
  final jni$_.JType<SystemColorsPlugin> $type;

  @jni$_.internal
  SystemColorsPlugin.fromReference(jni$_.JReference reference)
    : $type = type,
      super.fromReference(reference);

  static final _class = jni$_.JClass.forName(
    r'io/github/deminearchiver/system_colors_android/SystemColorsPlugin',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<SystemColorsPlugin?> nullableType =
      $SystemColorsPlugin$NullableType$();

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<SystemColorsPlugin> type =
      $SystemColorsPlugin$Type$();
  static final _id_INSTANCE = _class.staticFieldId(
    r'INSTANCE',
    r'Lio/github/deminearchiver/system_colors_android/SystemColorsPlugin;',
  );

  /// from: `static public final io.github.deminearchiver.system_colors_android.SystemColorsPlugin INSTANCE`
  /// The returned object must be released after use, by calling the [release] method.
  static SystemColorsPlugin get INSTANCE =>
      _id_INSTANCE.get(_class, const $SystemColorsPlugin$Type$());

  static final _id_isDynamicColorAvailable = _class.staticMethodId(
    r'isDynamicColorAvailable',
    r'()Z',
  );

  static final _isDynamicColorAvailable =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallStaticBooleanMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public fun isDynamicColorAvailable(): kotlin.Boolean`
  static bool isDynamicColorAvailable() {
    return _isDynamicColorAvailable(
      _class.reference.pointer,
      _id_isDynamicColorAvailable as jni$_.JMethodIDPtr,
    ).boolean;
  }
}

final class $SystemColorsPlugin$NullableType$
    extends jni$_.JType<SystemColorsPlugin?> {
  @jni$_.internal
  const $SystemColorsPlugin$NullableType$();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Lio/github/deminearchiver/system_colors_android/SystemColorsPlugin;';

  @jni$_.internal
  @core$_.override
  SystemColorsPlugin? fromReference(jni$_.JReference reference) =>
      reference.isNull ? null : SystemColorsPlugin.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$Type$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<SystemColorsPlugin?> get nullableType => this;

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($SystemColorsPlugin$NullableType$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($SystemColorsPlugin$NullableType$) &&
        other is $SystemColorsPlugin$NullableType$;
  }
}

final class $SystemColorsPlugin$Type$ extends jni$_.JType<SystemColorsPlugin> {
  @jni$_.internal
  const $SystemColorsPlugin$Type$();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Lio/github/deminearchiver/system_colors_android/SystemColorsPlugin;';

  @jni$_.internal
  @core$_.override
  SystemColorsPlugin fromReference(jni$_.JReference reference) =>
      SystemColorsPlugin.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$Type$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<SystemColorsPlugin?> get nullableType =>
      const $SystemColorsPlugin$NullableType$();

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($SystemColorsPlugin$Type$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($SystemColorsPlugin$Type$) &&
        other is $SystemColorsPlugin$Type$;
  }
}
