name: androidx_graphics_shapes
description: A library for easy creation, transformation, and morphing of rounded polygonal shapes. Contains predefined Material Design shapes that can be used at various components.
version: 1.7.0
homepage: https://github.com/deminearchiver/dart-flutter-packages
repository: https://github.com/deminearchiver/dart-flutter-packages/tree/main/packages/androidx_graphics_shapes
issue_tracker: https://github.com/deminearchiver/dart-flutter-packages/issues
resolution: workspace

environment:
  sdk: ^3.13.0
  flutter: ">=3.47.0"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.19.1
  material_3p: ^0.5.0
  meta: ^1.19.0
  vector_math: ^2.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  deminearchiver_lints: ^3.1.0
