// AUTO GENERATED BY JNIGEN 0.15.0. DO NOT EDIT!

// ignore_for_file: annotate_overrides
// ignore_for_file: argument_type_not_assignable
// ignore_for_file: camel_case_extensions
// ignore_for_file: camel_case_types
// ignore_for_file: constant_identifier_names
// ignore_for_file: comment_references
// ignore_for_file: doc_directive_unknown
// ignore_for_file: file_names
// ignore_for_file: inference_failure_on_untyped_parameter
// ignore_for_file: invalid_internal_annotation
// ignore_for_file: invalid_use_of_internal_member
// ignore_for_file: library_prefixes
// ignore_for_file: lines_longer_than_80_chars
// ignore_for_file: no_leading_underscores_for_library_prefixes
// ignore_for_file: no_leading_underscores_for_local_identifiers
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: only_throw_errors
// ignore_for_file: overridden_fields
// ignore_for_file: prefer_double_quotes
// ignore_for_file: unintended_html_in_doc_comment
// ignore_for_file: unnecessary_cast
// ignore_for_file: unnecessary_non_null_assertion
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: unused_element
// ignore_for_file: unused_field
// ignore_for_file: unused_import
// ignore_for_file: unused_local_variable
// ignore_for_file: unused_shown_name
// ignore_for_file: use_super_parameters

import 'dart:core' as core$_;
import 'dart:core' show Object, String, bool, double, int;

import 'package:jni/_internal.dart' as jni$_;
import 'package:jni/jni.dart' as jni$_;

/// from: `dev.deminearchiver.package_info_ffi.PackageInfoData`
class PackageInfoData extends jni$_.JObject {
  @jni$_.internal
  @core$_.override
  final jni$_.JType<PackageInfoData> $type;

  @jni$_.internal
  PackageInfoData.fromReference(jni$_.JReference reference)
    : $type = type,
      super.fromReference(reference);

  static final _class = jni$_.JClass.forName(
    r'dev/deminearchiver/package_info_ffi/PackageInfoData',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<PackageInfoData?> nullableType =
      $PackageInfoData$NullableType$();

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<PackageInfoData> type = $PackageInfoData$Type$();
  static final _id_new$ = _class.constructorId(
    r'(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;JJ)V',
  );

  static final _new$ =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Int64,
                    jni$_.Int64,
                  )
                >,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              int,
              int,
            )
          >();

  /// from: `public void <init>(java.lang.String string, java.lang.String string1, java.lang.String string2, java.lang.String string3, java.lang.String string4, java.lang.String string5, long j, long j1)`
  /// The returned object must be released after use, by calling the [release] method.
  factory PackageInfoData(
    jni$_.JString string,
    jni$_.JString string1,
    jni$_.JString string2,
    jni$_.JString string3,
    jni$_.JString? string4,
    jni$_.JString? string5,
    int j,
    int j1,
  ) {
    final _$string = string.reference;
    final _$string1 = string1.reference;
    final _$string2 = string2.reference;
    final _$string3 = string3.reference;
    final _$string4 = string4?.reference ?? jni$_.jNullReference;
    final _$string5 = string5?.reference ?? jni$_.jNullReference;
    return PackageInfoData.fromReference(
      _new$(
        _class.reference.pointer,
        _id_new$ as jni$_.JMethodIDPtr,
        _$string.pointer,
        _$string1.pointer,
        _$string2.pointer,
        _$string3.pointer,
        _$string4.pointer,
        _$string5.pointer,
        j,
        j1,
      ).reference,
    );
  }

  static final _id_new$1 = _class.constructorId(
    r'(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;JJILkotlin/jvm/internal/DefaultConstructorMarker;)V',
  );

  static final _new$1 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Int64,
                    jni$_.Int64,
                    jni$_.Int32,
                    jni$_.Pointer<jni$_.Void>,
                  )
                >,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              int,
              int,
              int,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `synthetic public void <init>(java.lang.String string, java.lang.String string1, java.lang.String string2, java.lang.String string3, java.lang.String string4, java.lang.String string5, long j, long j1, int i, kotlin.jvm.internal.DefaultConstructorMarker defaultConstructorMarker)`
  /// The returned object must be released after use, by calling the [release] method.
  factory PackageInfoData.new$1(
    jni$_.JString? string,
    jni$_.JString? string1,
    jni$_.JString? string2,
    jni$_.JString? string3,
    jni$_.JString? string4,
    jni$_.JString? string5,
    int j,
    int j1,
    int i,
    jni$_.JObject? defaultConstructorMarker,
  ) {
    final _$string = string?.reference ?? jni$_.jNullReference;
    final _$string1 = string1?.reference ?? jni$_.jNullReference;
    final _$string2 = string2?.reference ?? jni$_.jNullReference;
    final _$string3 = string3?.reference ?? jni$_.jNullReference;
    final _$string4 = string4?.reference ?? jni$_.jNullReference;
    final _$string5 = string5?.reference ?? jni$_.jNullReference;
    final _$defaultConstructorMarker =
        defaultConstructorMarker?.reference ?? jni$_.jNullReference;
    return PackageInfoData.fromReference(
      _new$1(
        _class.reference.pointer,
        _id_new$1 as jni$_.JMethodIDPtr,
        _$string.pointer,
        _$string1.pointer,
        _$string2.pointer,
        _$string3.pointer,
        _$string4.pointer,
        _$string5.pointer,
        j,
        j1,
        i,
        _$defaultConstructorMarker.pointer,
      ).reference,
    );
  }

  static final _id_getAppName = _class.instanceMethodId(
    r'getAppName',
    r'()Ljava/lang/String;',
  );

  static final _getAppName =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public final java.lang.String getAppName()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JString getAppName() {
    return _getAppName(
      reference.pointer,
      _id_getAppName as jni$_.JMethodIDPtr,
    ).object<jni$_.JString>(const jni$_.$JString$Type$());
  }

  static final _id_getPackageName = _class.instanceMethodId(
    r'getPackageName',
    r'()Ljava/lang/String;',
  );

  static final _getPackageName =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public final java.lang.String getPackageName()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JString getPackageName() {
    return _getPackageName(
      reference.pointer,
      _id_getPackageName as jni$_.JMethodIDPtr,
    ).object<jni$_.JString>(const jni$_.$JString$Type$());
  }

  static final _id_getVersion = _class.instanceMethodId(
    r'getVersion',
    r'()Ljava/lang/String;',
  );

  static final _getVersion =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public final java.lang.String getVersion()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JString getVersion() {
    return _getVersion(
      reference.pointer,
      _id_getVersion as jni$_.JMethodIDPtr,
    ).object<jni$_.JString>(const jni$_.$JString$Type$());
  }

  static final _id_getBuildNumber = _class.instanceMethodId(
    r'getBuildNumber',
    r'()Ljava/lang/String;',
  );

  static final _getBuildNumber =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public final java.lang.String getBuildNumber()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JString getBuildNumber() {
    return _getBuildNumber(
      reference.pointer,
      _id_getBuildNumber as jni$_.JMethodIDPtr,
    ).object<jni$_.JString>(const jni$_.$JString$Type$());
  }

  static final _id_getBuildSignature = _class.instanceMethodId(
    r'getBuildSignature',
    r'()Ljava/lang/String;',
  );

  static final _getBuildSignature =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public final java.lang.String getBuildSignature()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JString? getBuildSignature() {
    return _getBuildSignature(
      reference.pointer,
      _id_getBuildSignature as jni$_.JMethodIDPtr,
    ).object<jni$_.JString?>(const jni$_.$JString$NullableType$());
  }

  static final _id_getInstallerStore = _class.instanceMethodId(
    r'getInstallerStore',
    r'()Ljava/lang/String;',
  );

  static final _getInstallerStore =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public final java.lang.String getInstallerStore()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JString? getInstallerStore() {
    return _getInstallerStore(
      reference.pointer,
      _id_getInstallerStore as jni$_.JMethodIDPtr,
    ).object<jni$_.JString?>(const jni$_.$JString$NullableType$());
  }

  static final _id_getInstallTime = _class.instanceMethodId(
    r'getInstallTime',
    r'()J',
  );

  static final _getInstallTime =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallLongMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public final long getInstallTime()`
  int getInstallTime() {
    return _getInstallTime(
      reference.pointer,
      _id_getInstallTime as jni$_.JMethodIDPtr,
    ).long;
  }

  static final _id_getUpdateTime = _class.instanceMethodId(
    r'getUpdateTime',
    r'()J',
  );

  static final _getUpdateTime =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallLongMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public final long getUpdateTime()`
  int getUpdateTime() {
    return _getUpdateTime(
      reference.pointer,
      _id_getUpdateTime as jni$_.JMethodIDPtr,
    ).long;
  }
}

final class $PackageInfoData$NullableType$
    extends jni$_.JType<PackageInfoData?> {
  @jni$_.internal
  const $PackageInfoData$NullableType$();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Ldev/deminearchiver/package_info_ffi/PackageInfoData;';

  @jni$_.internal
  @core$_.override
  PackageInfoData? fromReference(jni$_.JReference reference) =>
      reference.isNull ? null : PackageInfoData.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$Type$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<PackageInfoData?> get nullableType => this;

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($PackageInfoData$NullableType$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($PackageInfoData$NullableType$) &&
        other is $PackageInfoData$NullableType$;
  }
}

final class $PackageInfoData$Type$ extends jni$_.JType<PackageInfoData> {
  @jni$_.internal
  const $PackageInfoData$Type$();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Ldev/deminearchiver/package_info_ffi/PackageInfoData;';

  @jni$_.internal
  @core$_.override
  PackageInfoData fromReference(jni$_.JReference reference) =>
      PackageInfoData.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$Type$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<PackageInfoData?> get nullableType =>
      const $PackageInfoData$NullableType$();

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($PackageInfoData$Type$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($PackageInfoData$Type$) &&
        other is $PackageInfoData$Type$;
  }
}

/// from: `dev.deminearchiver.package_info_ffi.PackageInfoPlugin`
class PackageInfoPlugin extends jni$_.JObject {
  @jni$_.internal
  @core$_.override
  final jni$_.JType<PackageInfoPlugin> $type;

  @jni$_.internal
  PackageInfoPlugin.fromReference(jni$_.JReference reference)
    : $type = type,
      super.fromReference(reference);

  static final _class = jni$_.JClass.forName(
    r'dev/deminearchiver/package_info_ffi/PackageInfoPlugin',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<PackageInfoPlugin?> nullableType =
      $PackageInfoPlugin$NullableType$();

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<PackageInfoPlugin> type = $PackageInfoPlugin$Type$();
  static final _id_INSTANCE = _class.staticFieldId(
    r'INSTANCE',
    r'Ldev/deminearchiver/package_info_ffi/PackageInfoPlugin;',
  );

  /// from: `static public final dev.deminearchiver.package_info_ffi.PackageInfoPlugin INSTANCE`
  /// The returned object must be released after use, by calling the [release] method.
  static PackageInfoPlugin get INSTANCE =>
      _id_INSTANCE.get(_class, const $PackageInfoPlugin$Type$());

  static final _id_getPackageInfo = _class.staticMethodId(
    r'getPackageInfo',
    r'(Landroid/content/Context;)Ldev/deminearchiver/package_info_ffi/PackageInfoData;',
  );

  static final _getPackageInfo =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallStaticObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public fun getPackageInfo(context: android.content.Context): dev.deminearchiver.package_info_ffi.PackageInfoData`
  /// The returned object must be released after use, by calling the [release] method.
  static PackageInfoData getPackageInfo(jni$_.JObject context) {
    final _$context = context.reference;
    return _getPackageInfo(
      _class.reference.pointer,
      _id_getPackageInfo as jni$_.JMethodIDPtr,
      _$context.pointer,
    ).object<PackageInfoData>(const $PackageInfoData$Type$());
  }
}

final class $PackageInfoPlugin$NullableType$
    extends jni$_.JType<PackageInfoPlugin?> {
  @jni$_.internal
  const $PackageInfoPlugin$NullableType$();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Ldev/deminearchiver/package_info_ffi/PackageInfoPlugin;';

  @jni$_.internal
  @core$_.override
  PackageInfoPlugin? fromReference(jni$_.JReference reference) =>
      reference.isNull ? null : PackageInfoPlugin.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$Type$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<PackageInfoPlugin?> get nullableType => this;

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($PackageInfoPlugin$NullableType$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($PackageInfoPlugin$NullableType$) &&
        other is $PackageInfoPlugin$NullableType$;
  }
}

final class $PackageInfoPlugin$Type$ extends jni$_.JType<PackageInfoPlugin> {
  @jni$_.internal
  const $PackageInfoPlugin$Type$();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Ldev/deminearchiver/package_info_ffi/PackageInfoPlugin;';

  @jni$_.internal
  @core$_.override
  PackageInfoPlugin fromReference(jni$_.JReference reference) =>
      PackageInfoPlugin.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$Type$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<PackageInfoPlugin?> get nullableType =>
      const $PackageInfoPlugin$NullableType$();

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($PackageInfoPlugin$Type$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($PackageInfoPlugin$Type$) &&
        other is $PackageInfoPlugin$Type$;
  }
}
