name: material
description: A Flutter library implementing Google's Material 3 Expressive design system.
version: 1.0.0
homepage: https://github.com/deminearchiver/dart-flutter-packages
repository: https://github.com/deminearchiver/dart-flutter-packages/tree/main/packages/material
issue_tracker: https://github.com/deminearchiver/dart-flutter-packages/issues
topics: [ui, widgets, material]
publish_to: none
resolution: workspace

environment:
  sdk: ^3.11.0
  flutter: ">=3.38.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  layout:
    path: ../layout
  androidx_graphics_shapes: ^1.3.2
  collection: ^1.19.1
  material_symbols_icons: ^4.2906.0
  meta: ^1.17.0
  libmonet: ^2.0.0-dev.10
  material_color_utilities: ^0.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  deminearchiver_lints: ^2.1.2
