name: material
description: A Flutter library implementing Google's Material 3 Expressive design system.
version: 1.0.0
homepage: https://github.com/deminearchiver/dart-flutter-packages
repository: https://github.com/deminearchiver/dart-flutter-packages/tree/main/packages/material
issue_tracker: https://github.com/deminearchiver/dart-flutter-packages/issues
topics: [ui, widgets, material]
publish_to: none
resolution: workspace

environment:
  sdk: ^3.11.0
  flutter: ">=3.41.0"

dependencies:
  # SDK dependencies
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Path dependencies
  layout:
    path: ../layout

  # Hosted dependencies
  androidx_graphics_shapes: ^1.4.0+1
  collection: ^1.19.1
  libmonet: ^2.0.0-dev.13
  material_symbols_icons: ^4.2928.1
  meta: ^1.17.0
  motor: ^1.1.0

dev_dependencies:
  # SDK dependencies
  flutter_test:
    sdk: flutter

  # Hosted dependencies
  deminearchiver_lints: ^2.1.2
