name: androidx_graphics_shapes_example
description: Example for the androidx_graphics_shapes package.
version: 0.1.0+1
publish_to: none
resolution: workspace

environment:
  sdk: ^3.13.0
  flutter: ">=3.47.0"

dependencies:
  flutter:
    sdk: flutter
  androidx_graphics_shapes:
    path: ../
  collection: ^1.19.1
  libmonet: 2.0.0-dev.22
  material_3p: ^0.5.0
  material_symbols_icons: ^4.2960.0
  meta: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  deminearchiver_lints: ^3.1.0

flutter:
  uses-material-design: true
