// AUTO GENERATED BY JNIGEN 0.17.0. DO NOT EDIT!

// ignore_for_file: annotate_overrides
// ignore_for_file: argument_type_not_assignable
// ignore_for_file: camel_case_extensions
// ignore_for_file: camel_case_types
// ignore_for_file: constant_identifier_names
// ignore_for_file: comment_references
// ignore_for_file: doc_directive_unknown
// ignore_for_file: file_names
// ignore_for_file: inference_failure_on_untyped_parameter
// ignore_for_file: invalid_internal_annotation
// ignore_for_file: invalid_use_of_internal_member
// ignore_for_file: library_prefixes
// ignore_for_file: lines_longer_than_80_chars
// ignore_for_file: no_leading_underscores_for_library_prefixes
// ignore_for_file: no_leading_underscores_for_local_identifiers
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: only_throw_errors
// ignore_for_file: overridden_fields
// ignore_for_file: prefer_double_quotes
// ignore_for_file: unintended_html_in_doc_comment
// ignore_for_file: unnecessary_cast
// ignore_for_file: unnecessary_non_null_assertion
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: unused_element
// ignore_for_file: unused_field
// ignore_for_file: unused_import
// ignore_for_file: unused_local_variable
// ignore_for_file: unused_shown_name
// ignore_for_file: use_super_parameters

import 'dart:core' as core$_;
import 'dart:core' show Object, String;

import 'package:jni/_internal.dart' as jni$_;
import 'package:jni/jni.dart' as jni$_;

const _$jniVersionCheck = jni$_.JniVersionCheck(1, 0);

/// from: `io.qzz.deminearchiver.system_colors_android.SystemColorsAndroidPlugin`
extension type SystemColorsAndroidPlugin._(jni$_.JObject _$this)
    implements jni$_.JObject, FlutterPlugin, MethodChannel$$MethodCallHandler {
  static final _class = jni$_.JClass.forName(
    r'io/qzz/deminearchiver/system_colors_android/SystemColorsAndroidPlugin',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<SystemColorsAndroidPlugin> type =
      $SystemColorsAndroidPlugin$Type$();
  static final _id_new$ = _class.constructorId(r'()V');

  static final _new$ =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public void <init>()`
  /// The returned object must be released after use, by calling the [release] method.
  factory SystemColorsAndroidPlugin() {
    final _$$classRef = _class.reference;
    return _new$(
      _$$classRef.pointer,
      _id_new$.pointer,
    ).object<SystemColorsAndroidPlugin>();
  }
}

extension SystemColorsAndroidPlugin$$Methods on SystemColorsAndroidPlugin {
  static final _id_onAttachedToEngine = SystemColorsAndroidPlugin._class
      .instanceMethodId(
        r'onAttachedToEngine',
        r'(Lio/flutter/embedding/engine/plugins/FlutterPlugin$FlutterPluginBinding;)V',
      );

  static final _onAttachedToEngine =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public fun onAttachedToEngine(flutterPluginBinding: io.flutter.embedding.engine.plugins.FlutterPlugin.FlutterPluginBinding): kotlin.Unit`
  void onAttachedToEngine(
    FlutterPlugin$$FlutterPluginBinding flutterPluginBinding,
  ) {
    final _$$selfRef = reference;
    final _$flutterPluginBinding = flutterPluginBinding.reference;
    _onAttachedToEngine(
      _$$selfRef.pointer,
      _id_onAttachedToEngine.pointer,
      _$flutterPluginBinding.pointer,
    ).check();
  }

  static final _id_onMethodCall = SystemColorsAndroidPlugin._class
      .instanceMethodId(
        r'onMethodCall',
        r'(Lio/flutter/plugin/common/MethodCall;Lio/flutter/plugin/common/MethodChannel$Result;)V',
      );

  static final _onMethodCall =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (jni$_.Pointer<jni$_.Void>, jni$_.Pointer<jni$_.Void>)
                >,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public fun onMethodCall(call: io.flutter.plugin.common.MethodCall, result: io.flutter.plugin.common.MethodChannel.Result): kotlin.Unit`
  void onMethodCall(MethodCall methodCall, MethodChannel$$Result result) {
    final _$$selfRef = reference;
    final _$methodCall = methodCall.reference;
    final _$result = result.reference;
    _onMethodCall(
      _$$selfRef.pointer,
      _id_onMethodCall.pointer,
      _$methodCall.pointer,
      _$result.pointer,
    ).check();
  }

  static final _id_onDetachedFromEngine = SystemColorsAndroidPlugin._class
      .instanceMethodId(
        r'onDetachedFromEngine',
        r'(Lio/flutter/embedding/engine/plugins/FlutterPlugin$FlutterPluginBinding;)V',
      );

  static final _onDetachedFromEngine =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public fun onDetachedFromEngine(binding: io.flutter.embedding.engine.plugins.FlutterPlugin.FlutterPluginBinding): kotlin.Unit`
  void onDetachedFromEngine(
    FlutterPlugin$$FlutterPluginBinding flutterPluginBinding,
  ) {
    final _$$selfRef = reference;
    final _$flutterPluginBinding = flutterPluginBinding.reference;
    _onDetachedFromEngine(
      _$$selfRef.pointer,
      _id_onDetachedFromEngine.pointer,
      _$flutterPluginBinding.pointer,
    ).check();
  }
}

final class $SystemColorsAndroidPlugin$Type$
    extends jni$_.JType<SystemColorsAndroidPlugin> {
  @jni$_.internal
  const $SystemColorsAndroidPlugin$Type$();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Lio/qzz/deminearchiver/system_colors_android/SystemColorsAndroidPlugin;';
}

/// from: `io.flutter.embedding.engine.plugins.FlutterPlugin$FlutterPluginBinding`
///
/// WARNING: FlutterPlugin$$FlutterPluginBinding is a stub. To generate bindings for this class, include
/// io.flutter.embedding.engine.plugins.FlutterPlugin$FlutterPluginBinding in your config's classes list.
///
extension type FlutterPlugin$$FlutterPluginBinding._(jni$_.JObject _$this)
    implements jni$_.JObject {
  static const jni$_.JType<FlutterPlugin$$FlutterPluginBinding> type =
      $FlutterPlugin$$FlutterPluginBinding$Type$();
}

final class $FlutterPlugin$$FlutterPluginBinding$Type$
    extends jni$_.JType<FlutterPlugin$$FlutterPluginBinding> {
  @jni$_.internal
  const $FlutterPlugin$$FlutterPluginBinding$Type$();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Lio/flutter/embedding/engine/plugins/FlutterPlugin$FlutterPluginBinding;';
}

/// from: `io.flutter.plugin.common.MethodCall`
///
/// WARNING: MethodCall is a stub. To generate bindings for this class, include
/// io.flutter.plugin.common.MethodCall in your config's classes list.
///
extension type MethodCall._(jni$_.JObject _$this) implements jni$_.JObject {
  static const jni$_.JType<MethodCall> type = $MethodCall$Type$();
}

final class $MethodCall$Type$ extends jni$_.JType<MethodCall> {
  @jni$_.internal
  const $MethodCall$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lio/flutter/plugin/common/MethodCall;';
}

/// from: `io.flutter.plugin.common.MethodChannel$Result`
///
/// WARNING: MethodChannel$$Result is a stub. To generate bindings for this class, include
/// io.flutter.plugin.common.MethodChannel$Result in your config's classes list.
///
extension type MethodChannel$$Result._(jni$_.JObject _$this)
    implements jni$_.JObject {
  static const jni$_.JType<MethodChannel$$Result> type =
      $MethodChannel$$Result$Type$();
}

final class $MethodChannel$$Result$Type$
    extends jni$_.JType<MethodChannel$$Result> {
  @jni$_.internal
  const $MethodChannel$$Result$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lio/flutter/plugin/common/MethodChannel$Result;';
}

/// from: `io.flutter.embedding.engine.plugins.FlutterPlugin`
///
/// WARNING: FlutterPlugin is a stub. To generate bindings for this class, include
/// io.flutter.embedding.engine.plugins.FlutterPlugin in your config's classes list.
///
extension type FlutterPlugin._(jni$_.JObject _$this) implements jni$_.JObject {
  static const jni$_.JType<FlutterPlugin> type = $FlutterPlugin$Type$();
}

final class $FlutterPlugin$Type$ extends jni$_.JType<FlutterPlugin> {
  @jni$_.internal
  const $FlutterPlugin$Type$();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Lio/flutter/embedding/engine/plugins/FlutterPlugin;';
}

/// from: `io.flutter.plugin.common.MethodChannel$MethodCallHandler`
///
/// WARNING: MethodChannel$$MethodCallHandler is a stub. To generate bindings for this class, include
/// io.flutter.plugin.common.MethodChannel$MethodCallHandler in your config's classes list.
///
extension type MethodChannel$$MethodCallHandler._(jni$_.JObject _$this)
    implements jni$_.JObject {
  static const jni$_.JType<MethodChannel$$MethodCallHandler> type =
      $MethodChannel$$MethodCallHandler$Type$();
}

final class $MethodChannel$$MethodCallHandler$Type$
    extends jni$_.JType<MethodChannel$$MethodCallHandler> {
  @jni$_.internal
  const $MethodChannel$$MethodCallHandler$Type$();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Lio/flutter/plugin/common/MethodChannel$MethodCallHandler;';
}
