// AUTO GENERATED BY JNIGEN 0.17.0. DO NOT EDIT!

// ignore_for_file: annotate_overrides
// ignore_for_file: argument_type_not_assignable
// ignore_for_file: camel_case_extensions
// ignore_for_file: camel_case_types
// ignore_for_file: constant_identifier_names
// ignore_for_file: comment_references
// ignore_for_file: doc_directive_unknown
// ignore_for_file: file_names
// ignore_for_file: inference_failure_on_untyped_parameter
// ignore_for_file: invalid_internal_annotation
// ignore_for_file: invalid_use_of_internal_member
// ignore_for_file: library_prefixes
// ignore_for_file: lines_longer_than_80_chars
// ignore_for_file: no_leading_underscores_for_library_prefixes
// ignore_for_file: no_leading_underscores_for_local_identifiers
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: only_throw_errors
// ignore_for_file: overridden_fields
// ignore_for_file: prefer_double_quotes
// ignore_for_file: unintended_html_in_doc_comment
// ignore_for_file: unnecessary_cast
// ignore_for_file: unnecessary_non_null_assertion
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: unused_element
// ignore_for_file: unused_field
// ignore_for_file: unused_import
// ignore_for_file: unused_local_variable
// ignore_for_file: unused_shown_name
// ignore_for_file: use_super_parameters

import 'dart:core' as core$_;
import 'dart:core' show Object, String;

import 'package:jni/_internal.dart' as jni$_;
import 'package:jni/jni.dart' as jni$_;

const _$jniVersionCheck = jni$_.JniVersionCheck(1, 0);

/// from: `io.qzz.deminearchiver.system_colors_android.SystemColorsPlugin`
extension type SystemColorsPlugin._(jni$_.JObject _$this)
    implements jni$_.JObject {
  static final _class = jni$_.JClass.forName(
    r'io/qzz/deminearchiver/system_colors_android/SystemColorsPlugin',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<SystemColorsPlugin> type =
      $SystemColorsPlugin$Type$();
  static final _id_get$isDynamicColorAvailable = _class.staticMethodId(
    r'isDynamicColorAvailable',
    r'()Z',
  );

  static final _get$isDynamicColorAvailable =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallStaticBooleanMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public fun isDynamicColorAvailable(): kotlin.Boolean`
  static core$_.bool get isDynamicColorAvailable {
    final _$$classRef = _class.reference;
    return _get$isDynamicColorAvailable(
      _$$classRef.pointer,
      _id_get$isDynamicColorAvailable.pointer,
    ).boolean;
  }

  static final _id_tonalPalettes = _class.staticMethodId(
    r'tonalPalettes',
    r'(Landroid/content/Context;I)Lio/qzz/deminearchiver/system_colors_android/SystemColorsTonalPalettes;',
  );

  static final _tonalPalettes =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>, jni$_.Int32)>,
              )
            >
          >('globalEnv_CallStaticObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              core$_.int,
            )
          >();

  /// from: `public fun tonalPalettes(context: android.content.Context, sentinel: kotlin.Int): io.qzz.deminearchiver.system_colors_android.SystemColorsTonalPalettes`
  /// The returned object must be released after use, by calling the [release] method.
  static SystemColorsTonalPalettes tonalPalettes(
    jni$_.JObject context,
    core$_.int i,
  ) {
    final _$$classRef = _class.reference;
    final _$context = context.reference;
    return _tonalPalettes(
      _$$classRef.pointer,
      _id_tonalPalettes.pointer,
      _$context.pointer,
      i,
    ).object<SystemColorsTonalPalettes>();
  }

  static final _id_colorScheme = _class.staticMethodId(
    r'colorScheme',
    r'(Landroid/content/Context;ZI)Lio/qzz/deminearchiver/system_colors_android/SystemColorsDynamicScheme;',
  );

  static final _colorScheme =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (jni$_.Pointer<jni$_.Void>, jni$_.Int32, jni$_.Int32)
                >,
              )
            >
          >('globalEnv_CallStaticObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              core$_.int,
              core$_.int,
            )
          >();

  /// from: `public fun colorScheme(context: android.content.Context, isDark: kotlin.Boolean, sentinel: kotlin.Int): io.qzz.deminearchiver.system_colors_android.SystemColorsDynamicScheme`
  /// The returned object must be released after use, by calling the [release] method.
  static SystemColorsDynamicScheme colorScheme(
    jni$_.JObject context,
    core$_.bool z,
    core$_.int i,
  ) {
    final _$$classRef = _class.reference;
    final _$context = context.reference;
    return _colorScheme(
      _$$classRef.pointer,
      _id_colorScheme.pointer,
      _$context.pointer,
      z ? 1 : 0,
      i,
    ).object<SystemColorsDynamicScheme>();
  }

  static final _id_lightColorScheme = _class.staticMethodId(
    r'lightColorScheme',
    r'(Landroid/content/Context;I)Lio/qzz/deminearchiver/system_colors_android/SystemColorsDynamicScheme;',
  );

  static final _lightColorScheme =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>, jni$_.Int32)>,
              )
            >
          >('globalEnv_CallStaticObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              core$_.int,
            )
          >();

  /// from: `public fun lightColorScheme(context: android.content.Context, sentinel: kotlin.Int): io.qzz.deminearchiver.system_colors_android.SystemColorsDynamicScheme`
  /// The returned object must be released after use, by calling the [release] method.
  static SystemColorsDynamicScheme lightColorScheme(
    jni$_.JObject context,
    core$_.int i,
  ) {
    final _$$classRef = _class.reference;
    final _$context = context.reference;
    return _lightColorScheme(
      _$$classRef.pointer,
      _id_lightColorScheme.pointer,
      _$context.pointer,
      i,
    ).object<SystemColorsDynamicScheme>();
  }

  static final _id_darkColorScheme = _class.staticMethodId(
    r'darkColorScheme',
    r'(Landroid/content/Context;I)Lio/qzz/deminearchiver/system_colors_android/SystemColorsDynamicScheme;',
  );

  static final _darkColorScheme =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>, jni$_.Int32)>,
              )
            >
          >('globalEnv_CallStaticObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              core$_.int,
            )
          >();

  /// from: `public fun darkColorScheme(context: android.content.Context, sentinel: kotlin.Int): io.qzz.deminearchiver.system_colors_android.SystemColorsDynamicScheme`
  /// The returned object must be released after use, by calling the [release] method.
  static SystemColorsDynamicScheme darkColorScheme(
    jni$_.JObject context,
    core$_.int i,
  ) {
    final _$$classRef = _class.reference;
    final _$context = context.reference;
    return _darkColorScheme(
      _$$classRef.pointer,
      _id_darkColorScheme.pointer,
      _$context.pointer,
      i,
    ).object<SystemColorsDynamicScheme>();
  }
}

final class $SystemColorsPlugin$Type$ extends jni$_.JType<SystemColorsPlugin> {
  @jni$_.internal
  const $SystemColorsPlugin$Type$();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Lio/qzz/deminearchiver/system_colors_android/SystemColorsPlugin;';
}

/// from: `io.qzz.deminearchiver.system_colors_android.SystemColorsTonalPalettes$Companion`
extension type SystemColorsTonalPalettes$Companion._(jni$_.JObject _$this)
    implements jni$_.JObject {
  static final _class = jni$_.JClass.forName(
    r'io/qzz/deminearchiver/system_colors_android/SystemColorsTonalPalettes$Companion',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<SystemColorsTonalPalettes$Companion> type =
      $SystemColorsTonalPalettes$Companion$Type$();
  static final _id_new$ = _class.constructorId(
    r'(Lkotlin/jvm/internal/DefaultConstructorMarker;)V',
  );

  static final _new$ =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `synthetic public void <init>(kotlin.jvm.internal.DefaultConstructorMarker defaultConstructorMarker)`
  /// The returned object must be released after use, by calling the [release] method.
  factory SystemColorsTonalPalettes$Companion(
    jni$_.JObject? defaultConstructorMarker,
  ) {
    final _$$classRef = _class.reference;
    final _$defaultConstructorMarker =
        defaultConstructorMarker?.reference ?? jni$_.jNullReference;
    return _new$(
      _$$classRef.pointer,
      _id_new$.pointer,
      _$defaultConstructorMarker.pointer,
    ).object<SystemColorsTonalPalettes$Companion>();
  }
}

extension SystemColorsTonalPalettes$Companion$$Methods
    on SystemColorsTonalPalettes$Companion {
  static final _id_empty = SystemColorsTonalPalettes$Companion._class
      .instanceMethodId(
        r'empty',
        r'(I)Lio/qzz/deminearchiver/system_colors_android/SystemColorsTonalPalettes;',
      );

  static final _empty =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Int32,)>,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.int,
            )
          >();

  /// from: `public fun empty(sentinel: kotlin.Int): io.qzz.deminearchiver.system_colors_android.SystemColorsTonalPalettes`
  /// The returned object must be released after use, by calling the [release] method.
  SystemColorsTonalPalettes empty(core$_.int i) {
    final _$$selfRef = reference;
    return _empty(
      _$$selfRef.pointer,
      _id_empty.pointer,
      i,
    ).object<SystemColorsTonalPalettes>();
  }

  static final _id_fromContext = SystemColorsTonalPalettes$Companion._class
      .instanceMethodId(
        r'fromContext',
        r'(Landroid/content/Context;I)Lio/qzz/deminearchiver/system_colors_android/SystemColorsTonalPalettes;',
      );

  static final _fromContext =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>, jni$_.Int32)>,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              core$_.int,
            )
          >();

  /// from: `public fun fromContext(context: android.content.Context, sentinel: kotlin.Int): io.qzz.deminearchiver.system_colors_android.SystemColorsTonalPalettes`
  /// The returned object must be released after use, by calling the [release] method.
  SystemColorsTonalPalettes fromContext(jni$_.JObject context, core$_.int i) {
    final _$$selfRef = reference;
    final _$context = context.reference;
    return _fromContext(
      _$$selfRef.pointer,
      _id_fromContext.pointer,
      _$context.pointer,
      i,
    ).object<SystemColorsTonalPalettes>();
  }
}

final class $SystemColorsTonalPalettes$Companion$Type$
    extends jni$_.JType<SystemColorsTonalPalettes$Companion> {
  @jni$_.internal
  const $SystemColorsTonalPalettes$Companion$Type$();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Lio/qzz/deminearchiver/system_colors_android/SystemColorsTonalPalettes$Companion;';
}

/// from: `io.qzz.deminearchiver.system_colors_android.SystemColorsTonalPalettes`
extension type SystemColorsTonalPalettes._(jni$_.JObject _$this)
    implements jni$_.JObject {
  static final _class = jni$_.JClass.forName(
    r'io/qzz/deminearchiver/system_colors_android/SystemColorsTonalPalettes',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<SystemColorsTonalPalettes> type =
      $SystemColorsTonalPalettes$Type$();
  static final _id_empty = _class.staticMethodId(
    r'empty',
    r'(I)Lio/qzz/deminearchiver/system_colors_android/SystemColorsTonalPalettes;',
  );

  static final _empty =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Int32,)>,
              )
            >
          >('globalEnv_CallStaticObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.int,
            )
          >();

  /// from: `static public final io.qzz.deminearchiver.system_colors_android.SystemColorsTonalPalettes empty(int i)`
  /// The returned object must be released after use, by calling the [release] method.
  static SystemColorsTonalPalettes empty(core$_.int i) {
    final _$$classRef = _class.reference;
    return _empty(
      _$$classRef.pointer,
      _id_empty.pointer,
      i,
    ).object<SystemColorsTonalPalettes>();
  }

  static final _id_fromContext = _class.staticMethodId(
    r'fromContext',
    r'(Landroid/content/Context;I)Lio/qzz/deminearchiver/system_colors_android/SystemColorsTonalPalettes;',
  );

  static final _fromContext =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>, jni$_.Int32)>,
              )
            >
          >('globalEnv_CallStaticObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              core$_.int,
            )
          >();

  /// from: `static public final io.qzz.deminearchiver.system_colors_android.SystemColorsTonalPalettes fromContext(android.content.Context context, int i)`
  /// The returned object must be released after use, by calling the [release] method.
  static SystemColorsTonalPalettes fromContext(
    jni$_.JObject context,
    core$_.int i,
  ) {
    final _$$classRef = _class.reference;
    final _$context = context.reference;
    return _fromContext(
      _$$classRef.pointer,
      _id_fromContext.pointer,
      _$context.pointer,
      i,
    ).object<SystemColorsTonalPalettes>();
  }

  static final _id_new$ = _class.constructorId(
    r'(IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIILkotlin/jvm/internal/DefaultConstructorMarker;)V',
  );

  static final _new$ =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Pointer<jni$_.Void>,
                  )
                >,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `synthetic public void <init>(int i, int i1, int i2, int i3, int i4, int i5, int i6, int i7, int i8, int i9, int i10, int i11, int i12, int i13, int i14, int i15, int i16, int i17, int i18, int i19, int i20, int i21, int i22, int i23, int i24, int i25, int i26, int i27, int i28, int i29, int i30, int i31, int i32, int i33, int i34, int i35, int i36, int i37, int i38, int i39, int i40, int i41, int i42, int i43, int i44, int i45, int i46, int i47, int i48, int i49, int i50, int i51, int i52, int i53, int i54, int i55, int i56, int i57, int i58, int i59, int i60, int i61, int i62, int i63, int i64, int i65, int i66, int i67, int i68, int i69, int i70, int i71, int i72, int i73, int i74, int i75, int i76, int i77, kotlin.jvm.internal.DefaultConstructorMarker defaultConstructorMarker)`
  /// The returned object must be released after use, by calling the [release] method.
  factory SystemColorsTonalPalettes(
    core$_.int i,
    core$_.int i1,
    core$_.int i2,
    core$_.int i3,
    core$_.int i4,
    core$_.int i5,
    core$_.int i6,
    core$_.int i7,
    core$_.int i8,
    core$_.int i9,
    core$_.int i10,
    core$_.int i11,
    core$_.int i12,
    core$_.int i13,
    core$_.int i14,
    core$_.int i15,
    core$_.int i16,
    core$_.int i17,
    core$_.int i18,
    core$_.int i19,
    core$_.int i20,
    core$_.int i21,
    core$_.int i22,
    core$_.int i23,
    core$_.int i24,
    core$_.int i25,
    core$_.int i26,
    core$_.int i27,
    core$_.int i28,
    core$_.int i29,
    core$_.int i30,
    core$_.int i31,
    core$_.int i32,
    core$_.int i33,
    core$_.int i34,
    core$_.int i35,
    core$_.int i36,
    core$_.int i37,
    core$_.int i38,
    core$_.int i39,
    core$_.int i40,
    core$_.int i41,
    core$_.int i42,
    core$_.int i43,
    core$_.int i44,
    core$_.int i45,
    core$_.int i46,
    core$_.int i47,
    core$_.int i48,
    core$_.int i49,
    core$_.int i50,
    core$_.int i51,
    core$_.int i52,
    core$_.int i53,
    core$_.int i54,
    core$_.int i55,
    core$_.int i56,
    core$_.int i57,
    core$_.int i58,
    core$_.int i59,
    core$_.int i60,
    core$_.int i61,
    core$_.int i62,
    core$_.int i63,
    core$_.int i64,
    core$_.int i65,
    core$_.int i66,
    core$_.int i67,
    core$_.int i68,
    core$_.int i69,
    core$_.int i70,
    core$_.int i71,
    core$_.int i72,
    core$_.int i73,
    core$_.int i74,
    core$_.int i75,
    core$_.int i76,
    core$_.int i77,
    jni$_.JObject? defaultConstructorMarker,
  ) {
    final _$$classRef = _class.reference;
    final _$defaultConstructorMarker =
        defaultConstructorMarker?.reference ?? jni$_.jNullReference;
    return _new$(
      _$$classRef.pointer,
      _id_new$.pointer,
      i,
      i1,
      i2,
      i3,
      i4,
      i5,
      i6,
      i7,
      i8,
      i9,
      i10,
      i11,
      i12,
      i13,
      i14,
      i15,
      i16,
      i17,
      i18,
      i19,
      i20,
      i21,
      i22,
      i23,
      i24,
      i25,
      i26,
      i27,
      i28,
      i29,
      i30,
      i31,
      i32,
      i33,
      i34,
      i35,
      i36,
      i37,
      i38,
      i39,
      i40,
      i41,
      i42,
      i43,
      i44,
      i45,
      i46,
      i47,
      i48,
      i49,
      i50,
      i51,
      i52,
      i53,
      i54,
      i55,
      i56,
      i57,
      i58,
      i59,
      i60,
      i61,
      i62,
      i63,
      i64,
      i65,
      i66,
      i67,
      i68,
      i69,
      i70,
      i71,
      i72,
      i73,
      i74,
      i75,
      i76,
      i77,
      _$defaultConstructorMarker.pointer,
    ).object<SystemColorsTonalPalettes>();
  }
}

extension SystemColorsTonalPalettes$$Methods on SystemColorsTonalPalettes {
  static final _id_primary0 = SystemColorsTonalPalettes._class.instanceFieldId(
    r'primary0',
    r'I',
  );

  /// from: `public final int primary0`
  core$_.int get primary0 =>
      _id_primary0.getNullable(this, jni$_.jint.type) as core$_.int;

  static final _id_primary10 = SystemColorsTonalPalettes._class.instanceFieldId(
    r'primary10',
    r'I',
  );

  /// from: `public final int primary10`
  core$_.int get primary10 =>
      _id_primary10.getNullable(this, jni$_.jint.type) as core$_.int;

  static final _id_primary20 = SystemColorsTonalPalettes._class.instanceFieldId(
    r'primary20',
    r'I',
  );

  /// from: `public final int primary20`
  core$_.int get primary20 =>
      _id_primary20.getNullable(this, jni$_.jint.type) as core$_.int;

  static final _id_primary30 = SystemColorsTonalPalettes._class.instanceFieldId(
    r'primary30',
    r'I',
  );

  /// from: `public final int primary30`
  core$_.int get primary30 =>
      _id_primary30.getNullable(this, jni$_.jint.type) as core$_.int;

  static final _id_primary40 = SystemColorsTonalPalettes._class.instanceFieldId(
    r'primary40',
    r'I',
  );

  /// from: `public final int primary40`
  core$_.int get primary40 =>
      _id_primary40.getNullable(this, jni$_.jint.type) as core$_.int;

  static final _id_primary50 = SystemColorsTonalPalettes._class.instanceFieldId(
    r'primary50',
    r'I',
  );

  /// from: `public final int primary50`
  core$_.int get primary50 =>
      _id_primary50.getNullable(this, jni$_.jint.type) as core$_.int;

  static final _id_primary60 = SystemColorsTonalPalettes._class.instanceFieldId(
    r'primary60',
    r'I',
  );

  /// from: `public final int primary60`
  core$_.int get primary60 =>
      _id_primary60.getNullable(this, jni$_.jint.type) as core$_.int;

  static final _id_primary70 = SystemColorsTonalPalettes._class.instanceFieldId(
    r'primary70',
    r'I',
  );

  /// from: `public final int primary70`
  core$_.int get primary70 =>
      _id_primary70.getNullable(this, jni$_.jint.type) as core$_.int;

  static final _id_primary80 = SystemColorsTonalPalettes._class.instanceFieldId(
    r'primary80',
    r'I',
  );

  /// from: `public final int primary80`
  core$_.int get primary80 =>
      _id_primary80.getNullable(this, jni$_.jint.type) as core$_.int;

  static final _id_primary90 = SystemColorsTonalPalettes._class.instanceFieldId(
    r'primary90',
    r'I',
  );

  /// from: `public final int primary90`
  core$_.int get primary90 =>
      _id_primary90.getNullable(this, jni$_.jint.type) as core$_.int;

  static final _id_primary95 = SystemColorsTonalPalettes._class.instanceFieldId(
    r'primary95',
    r'I',
  );

  /// from: `public final int primary95`
  core$_.int get primary95 =>
      _id_primary95.getNullable(this, jni$_.jint.type) as core$_.int;

  static final _id_primary99 = SystemColorsTonalPalettes._class.instanceFieldId(
    r'primary99',
    r'I',
  );

  /// from: `public final int primary99`
  core$_.int get primary99 =>
      _id_primary99.getNullable(this, jni$_.jint.type) as core$_.int;

  static final _id_primary100 = SystemColorsTonalPalettes._class
      .instanceFieldId(r'primary100', r'I');

  /// from: `public final int primary100`
  core$_.int get primary100 =>
      _id_primary100.getNullable(this, jni$_.jint.type) as core$_.int;

  static final _id_secondary0 = SystemColorsTonalPalettes._class
      .instanceFieldId(r'secondary0', r'I');

  /// from: `public final int secondary0`
  core$_.int get secondary0 =>
      _id_secondary0.getNullable(this, jni$_.jint.type) as core$_.int;

  static final _id_secondary10 = SystemColorsTonalPalettes._class
      .instanceFieldId(r'secondary10', r'I');

  /// from: `public final int secondary10`
  core$_.int get secondary10 =>
      _id_secondary10.getNullable(this, jni$_.jint.type) as core$_.int;

  static final _id_secondary20 = SystemColorsTonalPalettes._class
      .instanceFieldId(r'secondary20', r'I');

  /// from: `public final int secondary20`
  core$_.int get secondary20 =>
      _id_secondary20.getNullable(this, jni$_.jint.type) as core$_.int;

  static final _id_secondary30 = SystemColorsTonalPalettes._class
      .instanceFieldId(r'secondary30', r'I');

  /// from: `public final int secondary30`
  core$_.int get secondary30 =>
      _id_secondary30.getNullable(this, jni$_.jint.type) as core$_.int;

  static final _id_secondary40 = SystemColorsTonalPalettes._class
      .instanceFieldId(r'secondary40', r'I');

  /// from: `public final int secondary40`
  core$_.int get secondary40 =>
      _id_secondary40.getNullable(this, jni$_.jint.type) as core$_.int;

  static final _id_secondary50 = SystemColorsTonalPalettes._class
      .instanceFieldId(r'secondary50', r'I');

  /// from: `public final int secondary50`
  core$_.int get secondary50 =>
      _id_secondary50.getNullable(this, jni$_.jint.type) as core$_.int;

  static final _id_secondary60 = SystemColorsTonalPalettes._class
      .instanceFieldId(r'secondary60', r'I');

  /// from: `public final int secondary60`
  core$_.int get secondary60 =>
      _id_secondary60.getNullable(this, jni$_.jint.type) as core$_.int;

  static final _id_secondary70 = SystemColorsTonalPalettes._class
      .instanceFieldId(r'secondary70', r'I');

  /// from: `public final int secondary70`
  core$_.int get secondary70 =>
      _id_secondary70.getNullable(this, jni$_.jint.type) as core$_.int;

  static final _id_secondary80 = SystemColorsTonalPalettes._class
      .instanceFieldId(r'secondary80', r'I');

  /// from: `public final int secondary80`
  core$_.int get secondary80 =>
      _id_secondary80.getNullable(this, jni$_.jint.type) as core$_.int;

  static final _id_secondary90 = SystemColorsTonalPalettes._class
      .instanceFieldId(r'secondary90', r'I');

  /// from: `public final int secondary90`
  core$_.int get secondary90 =>
      _id_secondary90.getNullable(this, jni$_.jint.type) as core$_.int;

  static final _id_secondary95 = SystemColorsTonalPalettes._class
      .instanceFieldId(r'secondary95', r'I');

  /// from: `public final int secondary95`
  core$_.int get secondary95 =>
      _id_secondary95.getNullable(this, jni$_.jint.type) as core$_.int;

  static final _id_secondary99 = SystemColorsTonalPalettes._class
      .instanceFieldId(r'secondary99', r'I');

  /// from: `public final int secondary99`
  core$_.int get secondary99 =>
      _id_secondary99.getNullable(this, jni$_.jint.type) as core$_.int;

  static final _id_secondary100 = SystemColorsTonalPalettes._class
      .instanceFieldId(r'secondary100', r'I');

  /// from: `public final int secondary100`
  core$_.int get secondary100 =>
      _id_secondary100.getNullable(this, jni$_.jint.type) as core$_.int;

  static final _id_tertiary0 = SystemColorsTonalPalettes._class.instanceFieldId(
    r'tertiary0',
    r'I',
  );

  /// from: `public final int tertiary0`
  core$_.int get tertiary0 =>
      _id_tertiary0.getNullable(this, jni$_.jint.type) as core$_.int;

  static final _id_tertiary10 = SystemColorsTonalPalettes._class
      .instanceFieldId(r'tertiary10', r'I');

  /// from: `public final int tertiary10`
  core$_.int get tertiary10 =>
      _id_tertiary10.getNullable(this, jni$_.jint.type) as core$_.int;

  static final _id_tertiary20 = SystemColorsTonalPalettes._class
      .instanceFieldId(r'tertiary20', r'I');

  /// from: `public final int tertiary20`
  core$_.int get tertiary20 =>
      _id_tertiary20.getNullable(this, jni$_.jint.type) as core$_.int;

  static final _id_tertiary30 = SystemColorsTonalPalettes._class
      .instanceFieldId(r'tertiary30', r'I');

  /// from: `public final int tertiary30`
  core$_.int get tertiary30 =>
      _id_tertiary30.getNullable(this, jni$_.jint.type) as core$_.int;

  static final _id_tertiary40 = SystemColorsTonalPalettes._class
      .instanceFieldId(r'tertiary40', r'I');

  /// from: `public final int tertiary40`
  core$_.int get tertiary40 =>
      _id_tertiary40.getNullable(this, jni$_.jint.type) as core$_.int;

  static final _id_tertiary50 = SystemColorsTonalPalettes._class
      .instanceFieldId(r'tertiary50', r'I');

  /// from: `public final int tertiary50`
  core$_.int get tertiary50 =>
      _id_tertiary50.getNullable(this, jni$_.jint.type) as core$_.int;

  static final _id_tertiary60 = SystemColorsTonalPalettes._class
      .instanceFieldId(r'tertiary60', r'I');

  /// from: `public final int tertiary60`
  core$_.int get tertiary60 =>
      _id_tertiary60.getNullable(this, jni$_.jint.type) as core$_.int;

  static final _id_tertiary70 = SystemColorsTonalPalettes._class
      .instanceFieldId(r'tertiary70', r'I');

  /// from: `public final int tertiary70`
  core$_.int get tertiary70 =>
      _id_tertiary70.getNullable(this, jni$_.jint.type) as core$_.int;

  static final _id_tertiary80 = SystemColorsTonalPalettes._class
      .instanceFieldId(r'tertiary80', r'I');

  /// from: `public final int tertiary80`
  core$_.int get tertiary80 =>
      _id_tertiary80.getNullable(this, jni$_.jint.type) as core$_.int;

  static final _id_tertiary90 = SystemColorsTonalPalettes._class
      .instanceFieldId(r'tertiary90', r'I');

  /// from: `public final int tertiary90`
  core$_.int get tertiary90 =>
      _id_tertiary90.getNullable(this, jni$_.jint.type) as core$_.int;

  static final _id_tertiary95 = SystemColorsTonalPalettes._class
      .instanceFieldId(r'tertiary95', r'I');

  /// from: `public final int tertiary95`
  core$_.int get tertiary95 =>
      _id_tertiary95.getNullable(this, jni$_.jint.type) as core$_.int;

  static final _id_tertiary99 = SystemColorsTonalPalettes._class
      .instanceFieldId(r'tertiary99', r'I');

  /// from: `public final int tertiary99`
  core$_.int get tertiary99 =>
      _id_tertiary99.getNullable(this, jni$_.jint.type) as core$_.int;

  static final _id_tertiary100 = SystemColorsTonalPalettes._class
      .instanceFieldId(r'tertiary100', r'I');

  /// from: `public final int tertiary100`
  core$_.int get tertiary100 =>
      _id_tertiary100.getNullable(this, jni$_.jint.type) as core$_.int;

  static final _id_neutral0 = SystemColorsTonalPalettes._class.instanceFieldId(
    r'neutral0',
    r'I',
  );

  /// from: `public final int neutral0`
  core$_.int get neutral0 =>
      _id_neutral0.getNullable(this, jni$_.jint.type) as core$_.int;

  static final _id_neutral10 = SystemColorsTonalPalettes._class.instanceFieldId(
    r'neutral10',
    r'I',
  );

  /// from: `public final int neutral10`
  core$_.int get neutral10 =>
      _id_neutral10.getNullable(this, jni$_.jint.type) as core$_.int;

  static final _id_neutral20 = SystemColorsTonalPalettes._class.instanceFieldId(
    r'neutral20',
    r'I',
  );

  /// from: `public final int neutral20`
  core$_.int get neutral20 =>
      _id_neutral20.getNullable(this, jni$_.jint.type) as core$_.int;

  static final _id_neutral30 = SystemColorsTonalPalettes._class.instanceFieldId(
    r'neutral30',
    r'I',
  );

  /// from: `public final int neutral30`
  core$_.int get neutral30 =>
      _id_neutral30.getNullable(this, jni$_.jint.type) as core$_.int;

  static final _id_neutral40 = SystemColorsTonalPalettes._class.instanceFieldId(
    r'neutral40',
    r'I',
  );

  /// from: `public final int neutral40`
  core$_.int get neutral40 =>
      _id_neutral40.getNullable(this, jni$_.jint.type) as core$_.int;

  static final _id_neutral50 = SystemColorsTonalPalettes._class.instanceFieldId(
    r'neutral50',
    r'I',
  );

  /// from: `public final int neutral50`
  core$_.int get neutral50 =>
      _id_neutral50.getNullable(this, jni$_.jint.type) as core$_.int;

  static final _id_neutral60 = SystemColorsTonalPalettes._class.instanceFieldId(
    r'neutral60',
    r'I',
  );

  /// from: `public final int neutral60`
  core$_.int get neutral60 =>
      _id_neutral60.getNullable(this, jni$_.jint.type) as core$_.int;

  static final _id_neutral70 = SystemColorsTonalPalettes._class.instanceFieldId(
    r'neutral70',
    r'I',
  );

  /// from: `public final int neutral70`
  core$_.int get neutral70 =>
      _id_neutral70.getNullable(this, jni$_.jint.type) as core$_.int;

  static final _id_neutral80 = SystemColorsTonalPalettes._class.instanceFieldId(
    r'neutral80',
    r'I',
  );

  /// from: `public final int neutral80`
  core$_.int get neutral80 =>
      _id_neutral80.getNullable(this, jni$_.jint.type) as core$_.int;

  static final _id_neutral90 = SystemColorsTonalPalettes._class.instanceFieldId(
    r'neutral90',
    r'I',
  );

  /// from: `public final int neutral90`
  core$_.int get neutral90 =>
      _id_neutral90.getNullable(this, jni$_.jint.type) as core$_.int;

  static final _id_neutral95 = SystemColorsTonalPalettes._class.instanceFieldId(
    r'neutral95',
    r'I',
  );

  /// from: `public final int neutral95`
  core$_.int get neutral95 =>
      _id_neutral95.getNullable(this, jni$_.jint.type) as core$_.int;

  static final _id_neutral99 = SystemColorsTonalPalettes._class.instanceFieldId(
    r'neutral99',
    r'I',
  );

  /// from: `public final int neutral99`
  core$_.int get neutral99 =>
      _id_neutral99.getNullable(this, jni$_.jint.type) as core$_.int;

  static final _id_neutral100 = SystemColorsTonalPalettes._class
      .instanceFieldId(r'neutral100', r'I');

  /// from: `public final int neutral100`
  core$_.int get neutral100 =>
      _id_neutral100.getNullable(this, jni$_.jint.type) as core$_.int;

  static final _id_neutralVariant0 = SystemColorsTonalPalettes._class
      .instanceFieldId(r'neutralVariant0', r'I');

  /// from: `public final int neutralVariant0`
  core$_.int get neutralVariant0 =>
      _id_neutralVariant0.getNullable(this, jni$_.jint.type) as core$_.int;

  static final _id_neutralVariant10 = SystemColorsTonalPalettes._class
      .instanceFieldId(r'neutralVariant10', r'I');

  /// from: `public final int neutralVariant10`
  core$_.int get neutralVariant10 =>
      _id_neutralVariant10.getNullable(this, jni$_.jint.type) as core$_.int;

  static final _id_neutralVariant20 = SystemColorsTonalPalettes._class
      .instanceFieldId(r'neutralVariant20', r'I');

  /// from: `public final int neutralVariant20`
  core$_.int get neutralVariant20 =>
      _id_neutralVariant20.getNullable(this, jni$_.jint.type) as core$_.int;

  static final _id_neutralVariant30 = SystemColorsTonalPalettes._class
      .instanceFieldId(r'neutralVariant30', r'I');

  /// from: `public final int neutralVariant30`
  core$_.int get neutralVariant30 =>
      _id_neutralVariant30.getNullable(this, jni$_.jint.type) as core$_.int;

  static final _id_neutralVariant40 = SystemColorsTonalPalettes._class
      .instanceFieldId(r'neutralVariant40', r'I');

  /// from: `public final int neutralVariant40`
  core$_.int get neutralVariant40 =>
      _id_neutralVariant40.getNullable(this, jni$_.jint.type) as core$_.int;

  static final _id_neutralVariant50 = SystemColorsTonalPalettes._class
      .instanceFieldId(r'neutralVariant50', r'I');

  /// from: `public final int neutralVariant50`
  core$_.int get neutralVariant50 =>
      _id_neutralVariant50.getNullable(this, jni$_.jint.type) as core$_.int;

  static final _id_neutralVariant60 = SystemColorsTonalPalettes._class
      .instanceFieldId(r'neutralVariant60', r'I');

  /// from: `public final int neutralVariant60`
  core$_.int get neutralVariant60 =>
      _id_neutralVariant60.getNullable(this, jni$_.jint.type) as core$_.int;

  static final _id_neutralVariant70 = SystemColorsTonalPalettes._class
      .instanceFieldId(r'neutralVariant70', r'I');

  /// from: `public final int neutralVariant70`
  core$_.int get neutralVariant70 =>
      _id_neutralVariant70.getNullable(this, jni$_.jint.type) as core$_.int;

  static final _id_neutralVariant80 = SystemColorsTonalPalettes._class
      .instanceFieldId(r'neutralVariant80', r'I');

  /// from: `public final int neutralVariant80`
  core$_.int get neutralVariant80 =>
      _id_neutralVariant80.getNullable(this, jni$_.jint.type) as core$_.int;

  static final _id_neutralVariant90 = SystemColorsTonalPalettes._class
      .instanceFieldId(r'neutralVariant90', r'I');

  /// from: `public final int neutralVariant90`
  core$_.int get neutralVariant90 =>
      _id_neutralVariant90.getNullable(this, jni$_.jint.type) as core$_.int;

  static final _id_neutralVariant95 = SystemColorsTonalPalettes._class
      .instanceFieldId(r'neutralVariant95', r'I');

  /// from: `public final int neutralVariant95`
  core$_.int get neutralVariant95 =>
      _id_neutralVariant95.getNullable(this, jni$_.jint.type) as core$_.int;

  static final _id_neutralVariant99 = SystemColorsTonalPalettes._class
      .instanceFieldId(r'neutralVariant99', r'I');

  /// from: `public final int neutralVariant99`
  core$_.int get neutralVariant99 =>
      _id_neutralVariant99.getNullable(this, jni$_.jint.type) as core$_.int;

  static final _id_neutralVariant100 = SystemColorsTonalPalettes._class
      .instanceFieldId(r'neutralVariant100', r'I');

  /// from: `public final int neutralVariant100`
  core$_.int get neutralVariant100 =>
      _id_neutralVariant100.getNullable(this, jni$_.jint.type) as core$_.int;

  static final _id_error0 = SystemColorsTonalPalettes._class.instanceFieldId(
    r'error0',
    r'I',
  );

  /// from: `public final int error0`
  core$_.int get error0 =>
      _id_error0.getNullable(this, jni$_.jint.type) as core$_.int;

  static final _id_error10 = SystemColorsTonalPalettes._class.instanceFieldId(
    r'error10',
    r'I',
  );

  /// from: `public final int error10`
  core$_.int get error10 =>
      _id_error10.getNullable(this, jni$_.jint.type) as core$_.int;

  static final _id_error20 = SystemColorsTonalPalettes._class.instanceFieldId(
    r'error20',
    r'I',
  );

  /// from: `public final int error20`
  core$_.int get error20 =>
      _id_error20.getNullable(this, jni$_.jint.type) as core$_.int;

  static final _id_error30 = SystemColorsTonalPalettes._class.instanceFieldId(
    r'error30',
    r'I',
  );

  /// from: `public final int error30`
  core$_.int get error30 =>
      _id_error30.getNullable(this, jni$_.jint.type) as core$_.int;

  static final _id_error40 = SystemColorsTonalPalettes._class.instanceFieldId(
    r'error40',
    r'I',
  );

  /// from: `public final int error40`
  core$_.int get error40 =>
      _id_error40.getNullable(this, jni$_.jint.type) as core$_.int;

  static final _id_error50 = SystemColorsTonalPalettes._class.instanceFieldId(
    r'error50',
    r'I',
  );

  /// from: `public final int error50`
  core$_.int get error50 =>
      _id_error50.getNullable(this, jni$_.jint.type) as core$_.int;

  static final _id_error60 = SystemColorsTonalPalettes._class.instanceFieldId(
    r'error60',
    r'I',
  );

  /// from: `public final int error60`
  core$_.int get error60 =>
      _id_error60.getNullable(this, jni$_.jint.type) as core$_.int;

  static final _id_error70 = SystemColorsTonalPalettes._class.instanceFieldId(
    r'error70',
    r'I',
  );

  /// from: `public final int error70`
  core$_.int get error70 =>
      _id_error70.getNullable(this, jni$_.jint.type) as core$_.int;

  static final _id_error80 = SystemColorsTonalPalettes._class.instanceFieldId(
    r'error80',
    r'I',
  );

  /// from: `public final int error80`
  core$_.int get error80 =>
      _id_error80.getNullable(this, jni$_.jint.type) as core$_.int;

  static final _id_error90 = SystemColorsTonalPalettes._class.instanceFieldId(
    r'error90',
    r'I',
  );

  /// from: `public final int error90`
  core$_.int get error90 =>
      _id_error90.getNullable(this, jni$_.jint.type) as core$_.int;

  static final _id_error95 = SystemColorsTonalPalettes._class.instanceFieldId(
    r'error95',
    r'I',
  );

  /// from: `public final int error95`
  core$_.int get error95 =>
      _id_error95.getNullable(this, jni$_.jint.type) as core$_.int;

  static final _id_error99 = SystemColorsTonalPalettes._class.instanceFieldId(
    r'error99',
    r'I',
  );

  /// from: `public final int error99`
  core$_.int get error99 =>
      _id_error99.getNullable(this, jni$_.jint.type) as core$_.int;

  static final _id_error100 = SystemColorsTonalPalettes._class.instanceFieldId(
    r'error100',
    r'I',
  );

  /// from: `public final int error100`
  core$_.int get error100 =>
      _id_error100.getNullable(this, jni$_.jint.type) as core$_.int;
}

final class $SystemColorsTonalPalettes$Type$
    extends jni$_.JType<SystemColorsTonalPalettes> {
  @jni$_.internal
  const $SystemColorsTonalPalettes$Type$();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Lio/qzz/deminearchiver/system_colors_android/SystemColorsTonalPalettes;';
}

/// from: `io.qzz.deminearchiver.system_colors_android.SystemColorsDynamicScheme$Companion`
extension type SystemColorsDynamicScheme$Companion._(jni$_.JObject _$this)
    implements jni$_.JObject {
  static final _class = jni$_.JClass.forName(
    r'io/qzz/deminearchiver/system_colors_android/SystemColorsDynamicScheme$Companion',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<SystemColorsDynamicScheme$Companion> type =
      $SystemColorsDynamicScheme$Companion$Type$();
  static final _id_new$ = _class.constructorId(
    r'(Lkotlin/jvm/internal/DefaultConstructorMarker;)V',
  );

  static final _new$ =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `synthetic public void <init>(kotlin.jvm.internal.DefaultConstructorMarker defaultConstructorMarker)`
  /// The returned object must be released after use, by calling the [release] method.
  factory SystemColorsDynamicScheme$Companion(
    jni$_.JObject? defaultConstructorMarker,
  ) {
    final _$$classRef = _class.reference;
    final _$defaultConstructorMarker =
        defaultConstructorMarker?.reference ?? jni$_.jNullReference;
    return _new$(
      _$$classRef.pointer,
      _id_new$.pointer,
      _$defaultConstructorMarker.pointer,
    ).object<SystemColorsDynamicScheme$Companion>();
  }
}

extension SystemColorsDynamicScheme$Companion$$Methods
    on SystemColorsDynamicScheme$Companion {
  static final _id_empty = SystemColorsDynamicScheme$Companion._class
      .instanceMethodId(
        r'empty',
        r'(I)Lio/qzz/deminearchiver/system_colors_android/SystemColorsDynamicScheme;',
      );

  static final _empty =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Int32,)>,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.int,
            )
          >();

  /// from: `public fun empty(sentinel: kotlin.Int): io.qzz.deminearchiver.system_colors_android.SystemColorsDynamicScheme`
  /// The returned object must be released after use, by calling the [release] method.
  SystemColorsDynamicScheme empty(core$_.int i) {
    final _$$selfRef = reference;
    return _empty(
      _$$selfRef.pointer,
      _id_empty.pointer,
      i,
    ).object<SystemColorsDynamicScheme>();
  }

  static final _id_fromContext = SystemColorsDynamicScheme$Companion._class
      .instanceMethodId(
        r'fromContext',
        r'(Landroid/content/Context;ZI)Lio/qzz/deminearchiver/system_colors_android/SystemColorsDynamicScheme;',
      );

  static final _fromContext =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (jni$_.Pointer<jni$_.Void>, jni$_.Int32, jni$_.Int32)
                >,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              core$_.int,
              core$_.int,
            )
          >();

  /// from: `public fun fromContext(context: android.content.Context, isDark: kotlin.Boolean, sentinel: kotlin.Int): io.qzz.deminearchiver.system_colors_android.SystemColorsDynamicScheme`
  /// The returned object must be released after use, by calling the [release] method.
  SystemColorsDynamicScheme fromContext(
    jni$_.JObject context,
    core$_.bool z,
    core$_.int i,
  ) {
    final _$$selfRef = reference;
    final _$context = context.reference;
    return _fromContext(
      _$$selfRef.pointer,
      _id_fromContext.pointer,
      _$context.pointer,
      z ? 1 : 0,
      i,
    ).object<SystemColorsDynamicScheme>();
  }

  static final _id_lightFromContext = SystemColorsDynamicScheme$Companion._class
      .instanceMethodId(
        r'lightFromContext',
        r'(Landroid/content/Context;I)Lio/qzz/deminearchiver/system_colors_android/SystemColorsDynamicScheme;',
      );

  static final _lightFromContext =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>, jni$_.Int32)>,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              core$_.int,
            )
          >();

  /// from: `public fun lightFromContext(context: android.content.Context, sentinel: kotlin.Int): io.qzz.deminearchiver.system_colors_android.SystemColorsDynamicScheme`
  /// The returned object must be released after use, by calling the [release] method.
  SystemColorsDynamicScheme lightFromContext(
    jni$_.JObject context,
    core$_.int i,
  ) {
    final _$$selfRef = reference;
    final _$context = context.reference;
    return _lightFromContext(
      _$$selfRef.pointer,
      _id_lightFromContext.pointer,
      _$context.pointer,
      i,
    ).object<SystemColorsDynamicScheme>();
  }

  static final _id_darkFromContext = SystemColorsDynamicScheme$Companion._class
      .instanceMethodId(
        r'darkFromContext',
        r'(Landroid/content/Context;I)Lio/qzz/deminearchiver/system_colors_android/SystemColorsDynamicScheme;',
      );

  static final _darkFromContext =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>, jni$_.Int32)>,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              core$_.int,
            )
          >();

  /// from: `public fun darkFromContext(context: android.content.Context, sentinel: kotlin.Int): io.qzz.deminearchiver.system_colors_android.SystemColorsDynamicScheme`
  /// The returned object must be released after use, by calling the [release] method.
  SystemColorsDynamicScheme darkFromContext(
    jni$_.JObject context,
    core$_.int i,
  ) {
    final _$$selfRef = reference;
    final _$context = context.reference;
    return _darkFromContext(
      _$$selfRef.pointer,
      _id_darkFromContext.pointer,
      _$context.pointer,
      i,
    ).object<SystemColorsDynamicScheme>();
  }
}

final class $SystemColorsDynamicScheme$Companion$Type$
    extends jni$_.JType<SystemColorsDynamicScheme$Companion> {
  @jni$_.internal
  const $SystemColorsDynamicScheme$Companion$Type$();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Lio/qzz/deminearchiver/system_colors_android/SystemColorsDynamicScheme$Companion;';
}

/// from: `io.qzz.deminearchiver.system_colors_android.SystemColorsDynamicScheme`
extension type SystemColorsDynamicScheme._(jni$_.JObject _$this)
    implements jni$_.JObject {
  static final _class = jni$_.JClass.forName(
    r'io/qzz/deminearchiver/system_colors_android/SystemColorsDynamicScheme',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<SystemColorsDynamicScheme> type =
      $SystemColorsDynamicScheme$Type$();
  static final _id_empty = _class.staticMethodId(
    r'empty',
    r'(I)Lio/qzz/deminearchiver/system_colors_android/SystemColorsDynamicScheme;',
  );

  static final _empty =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Int32,)>,
              )
            >
          >('globalEnv_CallStaticObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.int,
            )
          >();

  /// from: `static public final io.qzz.deminearchiver.system_colors_android.SystemColorsDynamicScheme empty(int i)`
  /// The returned object must be released after use, by calling the [release] method.
  static SystemColorsDynamicScheme empty(core$_.int i) {
    final _$$classRef = _class.reference;
    return _empty(
      _$$classRef.pointer,
      _id_empty.pointer,
      i,
    ).object<SystemColorsDynamicScheme>();
  }

  static final _id_fromContext = _class.staticMethodId(
    r'fromContext',
    r'(Landroid/content/Context;ZI)Lio/qzz/deminearchiver/system_colors_android/SystemColorsDynamicScheme;',
  );

  static final _fromContext =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (jni$_.Pointer<jni$_.Void>, jni$_.Int32, jni$_.Int32)
                >,
              )
            >
          >('globalEnv_CallStaticObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              core$_.int,
              core$_.int,
            )
          >();

  /// from: `static public final io.qzz.deminearchiver.system_colors_android.SystemColorsDynamicScheme fromContext(android.content.Context context, boolean z, int i)`
  /// The returned object must be released after use, by calling the [release] method.
  static SystemColorsDynamicScheme fromContext(
    jni$_.JObject context,
    core$_.bool z,
    core$_.int i,
  ) {
    final _$$classRef = _class.reference;
    final _$context = context.reference;
    return _fromContext(
      _$$classRef.pointer,
      _id_fromContext.pointer,
      _$context.pointer,
      z ? 1 : 0,
      i,
    ).object<SystemColorsDynamicScheme>();
  }

  static final _id_lightFromContext = _class.staticMethodId(
    r'lightFromContext',
    r'(Landroid/content/Context;I)Lio/qzz/deminearchiver/system_colors_android/SystemColorsDynamicScheme;',
  );

  static final _lightFromContext =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>, jni$_.Int32)>,
              )
            >
          >('globalEnv_CallStaticObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              core$_.int,
            )
          >();

  /// from: `static public final io.qzz.deminearchiver.system_colors_android.SystemColorsDynamicScheme lightFromContext(android.content.Context context, int i)`
  /// The returned object must be released after use, by calling the [release] method.
  static SystemColorsDynamicScheme lightFromContext(
    jni$_.JObject context,
    core$_.int i,
  ) {
    final _$$classRef = _class.reference;
    final _$context = context.reference;
    return _lightFromContext(
      _$$classRef.pointer,
      _id_lightFromContext.pointer,
      _$context.pointer,
      i,
    ).object<SystemColorsDynamicScheme>();
  }

  static final _id_darkFromContext = _class.staticMethodId(
    r'darkFromContext',
    r'(Landroid/content/Context;I)Lio/qzz/deminearchiver/system_colors_android/SystemColorsDynamicScheme;',
  );

  static final _darkFromContext =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>, jni$_.Int32)>,
              )
            >
          >('globalEnv_CallStaticObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              core$_.int,
            )
          >();

  /// from: `static public final io.qzz.deminearchiver.system_colors_android.SystemColorsDynamicScheme darkFromContext(android.content.Context context, int i)`
  /// The returned object must be released after use, by calling the [release] method.
  static SystemColorsDynamicScheme darkFromContext(
    jni$_.JObject context,
    core$_.int i,
  ) {
    final _$$classRef = _class.reference;
    final _$context = context.reference;
    return _darkFromContext(
      _$$classRef.pointer,
      _id_darkFromContext.pointer,
      _$context.pointer,
      i,
    ).object<SystemColorsDynamicScheme>();
  }

  static final _id_new$ = _class.constructorId(
    r'(IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIILkotlin/jvm/internal/DefaultConstructorMarker;)V',
  );

  static final _new$ =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Int32,
                    jni$_.Pointer<jni$_.Void>,
                  )
                >,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `synthetic public void <init>(int i, int i1, int i2, int i3, int i4, int i5, int i6, int i7, int i8, int i9, int i10, int i11, int i12, int i13, int i14, int i15, int i16, int i17, int i18, int i19, int i20, int i21, int i22, int i23, int i24, int i25, int i26, int i27, int i28, int i29, int i30, int i31, int i32, int i33, int i34, int i35, int i36, int i37, int i38, int i39, int i40, int i41, int i42, int i43, int i44, int i45, int i46, int i47, int i48, int i49, int i50, int i51, int i52, int i53, int i54, int i55, int i56, int i57, int i58, int i59, int i60, int i61, int i62, int i63, int i64, int i65, int i66, kotlin.jvm.internal.DefaultConstructorMarker defaultConstructorMarker)`
  /// The returned object must be released after use, by calling the [release] method.
  factory SystemColorsDynamicScheme(
    core$_.int i,
    core$_.int i1,
    core$_.int i2,
    core$_.int i3,
    core$_.int i4,
    core$_.int i5,
    core$_.int i6,
    core$_.int i7,
    core$_.int i8,
    core$_.int i9,
    core$_.int i10,
    core$_.int i11,
    core$_.int i12,
    core$_.int i13,
    core$_.int i14,
    core$_.int i15,
    core$_.int i16,
    core$_.int i17,
    core$_.int i18,
    core$_.int i19,
    core$_.int i20,
    core$_.int i21,
    core$_.int i22,
    core$_.int i23,
    core$_.int i24,
    core$_.int i25,
    core$_.int i26,
    core$_.int i27,
    core$_.int i28,
    core$_.int i29,
    core$_.int i30,
    core$_.int i31,
    core$_.int i32,
    core$_.int i33,
    core$_.int i34,
    core$_.int i35,
    core$_.int i36,
    core$_.int i37,
    core$_.int i38,
    core$_.int i39,
    core$_.int i40,
    core$_.int i41,
    core$_.int i42,
    core$_.int i43,
    core$_.int i44,
    core$_.int i45,
    core$_.int i46,
    core$_.int i47,
    core$_.int i48,
    core$_.int i49,
    core$_.int i50,
    core$_.int i51,
    core$_.int i52,
    core$_.int i53,
    core$_.int i54,
    core$_.int i55,
    core$_.int i56,
    core$_.int i57,
    core$_.int i58,
    core$_.int i59,
    core$_.int i60,
    core$_.int i61,
    core$_.int i62,
    core$_.int i63,
    core$_.int i64,
    core$_.int i65,
    core$_.int i66,
    jni$_.JObject? defaultConstructorMarker,
  ) {
    final _$$classRef = _class.reference;
    final _$defaultConstructorMarker =
        defaultConstructorMarker?.reference ?? jni$_.jNullReference;
    return _new$(
      _$$classRef.pointer,
      _id_new$.pointer,
      i,
      i1,
      i2,
      i3,
      i4,
      i5,
      i6,
      i7,
      i8,
      i9,
      i10,
      i11,
      i12,
      i13,
      i14,
      i15,
      i16,
      i17,
      i18,
      i19,
      i20,
      i21,
      i22,
      i23,
      i24,
      i25,
      i26,
      i27,
      i28,
      i29,
      i30,
      i31,
      i32,
      i33,
      i34,
      i35,
      i36,
      i37,
      i38,
      i39,
      i40,
      i41,
      i42,
      i43,
      i44,
      i45,
      i46,
      i47,
      i48,
      i49,
      i50,
      i51,
      i52,
      i53,
      i54,
      i55,
      i56,
      i57,
      i58,
      i59,
      i60,
      i61,
      i62,
      i63,
      i64,
      i65,
      i66,
      _$defaultConstructorMarker.pointer,
    ).object<SystemColorsDynamicScheme>();
  }
}

extension SystemColorsDynamicScheme$$Methods on SystemColorsDynamicScheme {
  static final _id_primaryPaletteKeyColor = SystemColorsDynamicScheme._class
      .instanceFieldId(r'primaryPaletteKeyColor', r'I');

  /// from: `public final int primaryPaletteKeyColor`
  core$_.int get primaryPaletteKeyColor =>
      _id_primaryPaletteKeyColor.getNullable(this, jni$_.jint.type)
          as core$_.int;

  static final _id_secondaryPaletteKeyColor = SystemColorsDynamicScheme._class
      .instanceFieldId(r'secondaryPaletteKeyColor', r'I');

  /// from: `public final int secondaryPaletteKeyColor`
  core$_.int get secondaryPaletteKeyColor =>
      _id_secondaryPaletteKeyColor.getNullable(this, jni$_.jint.type)
          as core$_.int;

  static final _id_tertiaryPaletteKeyColor = SystemColorsDynamicScheme._class
      .instanceFieldId(r'tertiaryPaletteKeyColor', r'I');

  /// from: `public final int tertiaryPaletteKeyColor`
  core$_.int get tertiaryPaletteKeyColor =>
      _id_tertiaryPaletteKeyColor.getNullable(this, jni$_.jint.type)
          as core$_.int;

  static final _id_neutralPaletteKeyColor = SystemColorsDynamicScheme._class
      .instanceFieldId(r'neutralPaletteKeyColor', r'I');

  /// from: `public final int neutralPaletteKeyColor`
  core$_.int get neutralPaletteKeyColor =>
      _id_neutralPaletteKeyColor.getNullable(this, jni$_.jint.type)
          as core$_.int;

  static final _id_neutralVariantPaletteKeyColor = SystemColorsDynamicScheme
      ._class
      .instanceFieldId(r'neutralVariantPaletteKeyColor', r'I');

  /// from: `public final int neutralVariantPaletteKeyColor`
  core$_.int get neutralVariantPaletteKeyColor =>
      _id_neutralVariantPaletteKeyColor.getNullable(this, jni$_.jint.type)
          as core$_.int;

  static final _id_errorPaletteKeyColor = SystemColorsDynamicScheme._class
      .instanceFieldId(r'errorPaletteKeyColor', r'I');

  /// from: `public final int errorPaletteKeyColor`
  core$_.int get errorPaletteKeyColor =>
      _id_errorPaletteKeyColor.getNullable(this, jni$_.jint.type) as core$_.int;

  static final _id_background = SystemColorsDynamicScheme._class
      .instanceFieldId(r'background', r'I');

  /// from: `public final int background`
  core$_.int get background =>
      _id_background.getNullable(this, jni$_.jint.type) as core$_.int;

  static final _id_onBackground = SystemColorsDynamicScheme._class
      .instanceFieldId(r'onBackground', r'I');

  /// from: `public final int onBackground`
  core$_.int get onBackground =>
      _id_onBackground.getNullable(this, jni$_.jint.type) as core$_.int;

  static final _id_surface = SystemColorsDynamicScheme._class.instanceFieldId(
    r'surface',
    r'I',
  );

  /// from: `public final int surface`
  core$_.int get surface =>
      _id_surface.getNullable(this, jni$_.jint.type) as core$_.int;

  static final _id_surfaceDim = SystemColorsDynamicScheme._class
      .instanceFieldId(r'surfaceDim', r'I');

  /// from: `public final int surfaceDim`
  core$_.int get surfaceDim =>
      _id_surfaceDim.getNullable(this, jni$_.jint.type) as core$_.int;

  static final _id_surfaceBright = SystemColorsDynamicScheme._class
      .instanceFieldId(r'surfaceBright', r'I');

  /// from: `public final int surfaceBright`
  core$_.int get surfaceBright =>
      _id_surfaceBright.getNullable(this, jni$_.jint.type) as core$_.int;

  static final _id_surfaceContainerLowest = SystemColorsDynamicScheme._class
      .instanceFieldId(r'surfaceContainerLowest', r'I');

  /// from: `public final int surfaceContainerLowest`
  core$_.int get surfaceContainerLowest =>
      _id_surfaceContainerLowest.getNullable(this, jni$_.jint.type)
          as core$_.int;

  static final _id_surfaceContainerLow = SystemColorsDynamicScheme._class
      .instanceFieldId(r'surfaceContainerLow', r'I');

  /// from: `public final int surfaceContainerLow`
  core$_.int get surfaceContainerLow =>
      _id_surfaceContainerLow.getNullable(this, jni$_.jint.type) as core$_.int;

  static final _id_surfaceContainer = SystemColorsDynamicScheme._class
      .instanceFieldId(r'surfaceContainer', r'I');

  /// from: `public final int surfaceContainer`
  core$_.int get surfaceContainer =>
      _id_surfaceContainer.getNullable(this, jni$_.jint.type) as core$_.int;

  static final _id_surfaceContainerHigh = SystemColorsDynamicScheme._class
      .instanceFieldId(r'surfaceContainerHigh', r'I');

  /// from: `public final int surfaceContainerHigh`
  core$_.int get surfaceContainerHigh =>
      _id_surfaceContainerHigh.getNullable(this, jni$_.jint.type) as core$_.int;

  static final _id_surfaceContainerHighest = SystemColorsDynamicScheme._class
      .instanceFieldId(r'surfaceContainerHighest', r'I');

  /// from: `public final int surfaceContainerHighest`
  core$_.int get surfaceContainerHighest =>
      _id_surfaceContainerHighest.getNullable(this, jni$_.jint.type)
          as core$_.int;

  static final _id_onSurface = SystemColorsDynamicScheme._class.instanceFieldId(
    r'onSurface',
    r'I',
  );

  /// from: `public final int onSurface`
  core$_.int get onSurface =>
      _id_onSurface.getNullable(this, jni$_.jint.type) as core$_.int;

  static final _id_surfaceVariant = SystemColorsDynamicScheme._class
      .instanceFieldId(r'surfaceVariant', r'I');

  /// from: `public final int surfaceVariant`
  core$_.int get surfaceVariant =>
      _id_surfaceVariant.getNullable(this, jni$_.jint.type) as core$_.int;

  static final _id_onSurfaceVariant = SystemColorsDynamicScheme._class
      .instanceFieldId(r'onSurfaceVariant', r'I');

  /// from: `public final int onSurfaceVariant`
  core$_.int get onSurfaceVariant =>
      _id_onSurfaceVariant.getNullable(this, jni$_.jint.type) as core$_.int;

  static final _id_outline = SystemColorsDynamicScheme._class.instanceFieldId(
    r'outline',
    r'I',
  );

  /// from: `public final int outline`
  core$_.int get outline =>
      _id_outline.getNullable(this, jni$_.jint.type) as core$_.int;

  static final _id_outlineVariant = SystemColorsDynamicScheme._class
      .instanceFieldId(r'outlineVariant', r'I');

  /// from: `public final int outlineVariant`
  core$_.int get outlineVariant =>
      _id_outlineVariant.getNullable(this, jni$_.jint.type) as core$_.int;

  static final _id_inverseSurface = SystemColorsDynamicScheme._class
      .instanceFieldId(r'inverseSurface', r'I');

  /// from: `public final int inverseSurface`
  core$_.int get inverseSurface =>
      _id_inverseSurface.getNullable(this, jni$_.jint.type) as core$_.int;

  static final _id_inverseOnSurface = SystemColorsDynamicScheme._class
      .instanceFieldId(r'inverseOnSurface', r'I');

  /// from: `public final int inverseOnSurface`
  core$_.int get inverseOnSurface =>
      _id_inverseOnSurface.getNullable(this, jni$_.jint.type) as core$_.int;

  static final _id_shadow = SystemColorsDynamicScheme._class.instanceFieldId(
    r'shadow',
    r'I',
  );

  /// from: `public final int shadow`
  core$_.int get shadow =>
      _id_shadow.getNullable(this, jni$_.jint.type) as core$_.int;

  static final _id_scrim = SystemColorsDynamicScheme._class.instanceFieldId(
    r'scrim',
    r'I',
  );

  /// from: `public final int scrim`
  core$_.int get scrim =>
      _id_scrim.getNullable(this, jni$_.jint.type) as core$_.int;

  static final _id_surfaceTint = SystemColorsDynamicScheme._class
      .instanceFieldId(r'surfaceTint', r'I');

  /// from: `public final int surfaceTint`
  core$_.int get surfaceTint =>
      _id_surfaceTint.getNullable(this, jni$_.jint.type) as core$_.int;

  static final _id_primary = SystemColorsDynamicScheme._class.instanceFieldId(
    r'primary',
    r'I',
  );

  /// from: `public final int primary`
  core$_.int get primary =>
      _id_primary.getNullable(this, jni$_.jint.type) as core$_.int;

  static final _id_primaryDim = SystemColorsDynamicScheme._class
      .instanceFieldId(r'primaryDim', r'I');

  /// from: `public final int primaryDim`
  core$_.int get primaryDim =>
      _id_primaryDim.getNullable(this, jni$_.jint.type) as core$_.int;

  static final _id_onPrimary = SystemColorsDynamicScheme._class.instanceFieldId(
    r'onPrimary',
    r'I',
  );

  /// from: `public final int onPrimary`
  core$_.int get onPrimary =>
      _id_onPrimary.getNullable(this, jni$_.jint.type) as core$_.int;

  static final _id_primaryContainer = SystemColorsDynamicScheme._class
      .instanceFieldId(r'primaryContainer', r'I');

  /// from: `public final int primaryContainer`
  core$_.int get primaryContainer =>
      _id_primaryContainer.getNullable(this, jni$_.jint.type) as core$_.int;

  static final _id_onPrimaryContainer = SystemColorsDynamicScheme._class
      .instanceFieldId(r'onPrimaryContainer', r'I');

  /// from: `public final int onPrimaryContainer`
  core$_.int get onPrimaryContainer =>
      _id_onPrimaryContainer.getNullable(this, jni$_.jint.type) as core$_.int;

  static final _id_primaryFixed = SystemColorsDynamicScheme._class
      .instanceFieldId(r'primaryFixed', r'I');

  /// from: `public final int primaryFixed`
  core$_.int get primaryFixed =>
      _id_primaryFixed.getNullable(this, jni$_.jint.type) as core$_.int;

  static final _id_primaryFixedDim = SystemColorsDynamicScheme._class
      .instanceFieldId(r'primaryFixedDim', r'I');

  /// from: `public final int primaryFixedDim`
  core$_.int get primaryFixedDim =>
      _id_primaryFixedDim.getNullable(this, jni$_.jint.type) as core$_.int;

  static final _id_onPrimaryFixed = SystemColorsDynamicScheme._class
      .instanceFieldId(r'onPrimaryFixed', r'I');

  /// from: `public final int onPrimaryFixed`
  core$_.int get onPrimaryFixed =>
      _id_onPrimaryFixed.getNullable(this, jni$_.jint.type) as core$_.int;

  static final _id_onPrimaryFixedVariant = SystemColorsDynamicScheme._class
      .instanceFieldId(r'onPrimaryFixedVariant', r'I');

  /// from: `public final int onPrimaryFixedVariant`
  core$_.int get onPrimaryFixedVariant =>
      _id_onPrimaryFixedVariant.getNullable(this, jni$_.jint.type)
          as core$_.int;

  static final _id_inversePrimary = SystemColorsDynamicScheme._class
      .instanceFieldId(r'inversePrimary', r'I');

  /// from: `public final int inversePrimary`
  core$_.int get inversePrimary =>
      _id_inversePrimary.getNullable(this, jni$_.jint.type) as core$_.int;

  static final _id_secondary = SystemColorsDynamicScheme._class.instanceFieldId(
    r'secondary',
    r'I',
  );

  /// from: `public final int secondary`
  core$_.int get secondary =>
      _id_secondary.getNullable(this, jni$_.jint.type) as core$_.int;

  static final _id_secondaryDim = SystemColorsDynamicScheme._class
      .instanceFieldId(r'secondaryDim', r'I');

  /// from: `public final int secondaryDim`
  core$_.int get secondaryDim =>
      _id_secondaryDim.getNullable(this, jni$_.jint.type) as core$_.int;

  static final _id_onSecondary = SystemColorsDynamicScheme._class
      .instanceFieldId(r'onSecondary', r'I');

  /// from: `public final int onSecondary`
  core$_.int get onSecondary =>
      _id_onSecondary.getNullable(this, jni$_.jint.type) as core$_.int;

  static final _id_secondaryContainer = SystemColorsDynamicScheme._class
      .instanceFieldId(r'secondaryContainer', r'I');

  /// from: `public final int secondaryContainer`
  core$_.int get secondaryContainer =>
      _id_secondaryContainer.getNullable(this, jni$_.jint.type) as core$_.int;

  static final _id_onSecondaryContainer = SystemColorsDynamicScheme._class
      .instanceFieldId(r'onSecondaryContainer', r'I');

  /// from: `public final int onSecondaryContainer`
  core$_.int get onSecondaryContainer =>
      _id_onSecondaryContainer.getNullable(this, jni$_.jint.type) as core$_.int;

  static final _id_secondaryFixed = SystemColorsDynamicScheme._class
      .instanceFieldId(r'secondaryFixed', r'I');

  /// from: `public final int secondaryFixed`
  core$_.int get secondaryFixed =>
      _id_secondaryFixed.getNullable(this, jni$_.jint.type) as core$_.int;

  static final _id_secondaryFixedDim = SystemColorsDynamicScheme._class
      .instanceFieldId(r'secondaryFixedDim', r'I');

  /// from: `public final int secondaryFixedDim`
  core$_.int get secondaryFixedDim =>
      _id_secondaryFixedDim.getNullable(this, jni$_.jint.type) as core$_.int;

  static final _id_onSecondaryFixed = SystemColorsDynamicScheme._class
      .instanceFieldId(r'onSecondaryFixed', r'I');

  /// from: `public final int onSecondaryFixed`
  core$_.int get onSecondaryFixed =>
      _id_onSecondaryFixed.getNullable(this, jni$_.jint.type) as core$_.int;

  static final _id_onSecondaryFixedVariant = SystemColorsDynamicScheme._class
      .instanceFieldId(r'onSecondaryFixedVariant', r'I');

  /// from: `public final int onSecondaryFixedVariant`
  core$_.int get onSecondaryFixedVariant =>
      _id_onSecondaryFixedVariant.getNullable(this, jni$_.jint.type)
          as core$_.int;

  static final _id_tertiary = SystemColorsDynamicScheme._class.instanceFieldId(
    r'tertiary',
    r'I',
  );

  /// from: `public final int tertiary`
  core$_.int get tertiary =>
      _id_tertiary.getNullable(this, jni$_.jint.type) as core$_.int;

  static final _id_tertiaryDim = SystemColorsDynamicScheme._class
      .instanceFieldId(r'tertiaryDim', r'I');

  /// from: `public final int tertiaryDim`
  core$_.int get tertiaryDim =>
      _id_tertiaryDim.getNullable(this, jni$_.jint.type) as core$_.int;

  static final _id_onTertiary = SystemColorsDynamicScheme._class
      .instanceFieldId(r'onTertiary', r'I');

  /// from: `public final int onTertiary`
  core$_.int get onTertiary =>
      _id_onTertiary.getNullable(this, jni$_.jint.type) as core$_.int;

  static final _id_tertiaryContainer = SystemColorsDynamicScheme._class
      .instanceFieldId(r'tertiaryContainer', r'I');

  /// from: `public final int tertiaryContainer`
  core$_.int get tertiaryContainer =>
      _id_tertiaryContainer.getNullable(this, jni$_.jint.type) as core$_.int;

  static final _id_onTertiaryContainer = SystemColorsDynamicScheme._class
      .instanceFieldId(r'onTertiaryContainer', r'I');

  /// from: `public final int onTertiaryContainer`
  core$_.int get onTertiaryContainer =>
      _id_onTertiaryContainer.getNullable(this, jni$_.jint.type) as core$_.int;

  static final _id_tertiaryFixed = SystemColorsDynamicScheme._class
      .instanceFieldId(r'tertiaryFixed', r'I');

  /// from: `public final int tertiaryFixed`
  core$_.int get tertiaryFixed =>
      _id_tertiaryFixed.getNullable(this, jni$_.jint.type) as core$_.int;

  static final _id_tertiaryFixedDim = SystemColorsDynamicScheme._class
      .instanceFieldId(r'tertiaryFixedDim', r'I');

  /// from: `public final int tertiaryFixedDim`
  core$_.int get tertiaryFixedDim =>
      _id_tertiaryFixedDim.getNullable(this, jni$_.jint.type) as core$_.int;

  static final _id_onTertiaryFixed = SystemColorsDynamicScheme._class
      .instanceFieldId(r'onTertiaryFixed', r'I');

  /// from: `public final int onTertiaryFixed`
  core$_.int get onTertiaryFixed =>
      _id_onTertiaryFixed.getNullable(this, jni$_.jint.type) as core$_.int;

  static final _id_onTertiaryFixedVariant = SystemColorsDynamicScheme._class
      .instanceFieldId(r'onTertiaryFixedVariant', r'I');

  /// from: `public final int onTertiaryFixedVariant`
  core$_.int get onTertiaryFixedVariant =>
      _id_onTertiaryFixedVariant.getNullable(this, jni$_.jint.type)
          as core$_.int;

  static final _id_error = SystemColorsDynamicScheme._class.instanceFieldId(
    r'error',
    r'I',
  );

  /// from: `public final int error`
  core$_.int get error =>
      _id_error.getNullable(this, jni$_.jint.type) as core$_.int;

  static final _id_errorDim = SystemColorsDynamicScheme._class.instanceFieldId(
    r'errorDim',
    r'I',
  );

  /// from: `public final int errorDim`
  core$_.int get errorDim =>
      _id_errorDim.getNullable(this, jni$_.jint.type) as core$_.int;

  static final _id_onError = SystemColorsDynamicScheme._class.instanceFieldId(
    r'onError',
    r'I',
  );

  /// from: `public final int onError`
  core$_.int get onError =>
      _id_onError.getNullable(this, jni$_.jint.type) as core$_.int;

  static final _id_errorContainer = SystemColorsDynamicScheme._class
      .instanceFieldId(r'errorContainer', r'I');

  /// from: `public final int errorContainer`
  core$_.int get errorContainer =>
      _id_errorContainer.getNullable(this, jni$_.jint.type) as core$_.int;

  static final _id_onErrorContainer = SystemColorsDynamicScheme._class
      .instanceFieldId(r'onErrorContainer', r'I');

  /// from: `public final int onErrorContainer`
  core$_.int get onErrorContainer =>
      _id_onErrorContainer.getNullable(this, jni$_.jint.type) as core$_.int;

  static final _id_controlActivated = SystemColorsDynamicScheme._class
      .instanceFieldId(r'controlActivated', r'I');

  /// from: `public final int controlActivated`
  core$_.int get controlActivated =>
      _id_controlActivated.getNullable(this, jni$_.jint.type) as core$_.int;

  static final _id_controlNormal = SystemColorsDynamicScheme._class
      .instanceFieldId(r'controlNormal', r'I');

  /// from: `public final int controlNormal`
  core$_.int get controlNormal =>
      _id_controlNormal.getNullable(this, jni$_.jint.type) as core$_.int;

  static final _id_controlHighlight = SystemColorsDynamicScheme._class
      .instanceFieldId(r'controlHighlight', r'I');

  /// from: `public final int controlHighlight`
  core$_.int get controlHighlight =>
      _id_controlHighlight.getNullable(this, jni$_.jint.type) as core$_.int;

  static final _id_textPrimaryInverse = SystemColorsDynamicScheme._class
      .instanceFieldId(r'textPrimaryInverse', r'I');

  /// from: `public final int textPrimaryInverse`
  core$_.int get textPrimaryInverse =>
      _id_textPrimaryInverse.getNullable(this, jni$_.jint.type) as core$_.int;

  static final _id_textSecondaryAndTertiaryInverse = SystemColorsDynamicScheme
      ._class
      .instanceFieldId(r'textSecondaryAndTertiaryInverse', r'I');

  /// from: `public final int textSecondaryAndTertiaryInverse`
  core$_.int get textSecondaryAndTertiaryInverse =>
      _id_textSecondaryAndTertiaryInverse.getNullable(this, jni$_.jint.type)
          as core$_.int;

  static final _id_textPrimaryInverseDisableOnly = SystemColorsDynamicScheme
      ._class
      .instanceFieldId(r'textPrimaryInverseDisableOnly', r'I');

  /// from: `public final int textPrimaryInverseDisableOnly`
  core$_.int get textPrimaryInverseDisableOnly =>
      _id_textPrimaryInverseDisableOnly.getNullable(this, jni$_.jint.type)
          as core$_.int;

  static final _id_textSecondaryAndTertiaryInverseDisabled =
      SystemColorsDynamicScheme._class.instanceFieldId(
        r'textSecondaryAndTertiaryInverseDisabled',
        r'I',
      );

  /// from: `public final int textSecondaryAndTertiaryInverseDisabled`
  core$_.int get textSecondaryAndTertiaryInverseDisabled =>
      _id_textSecondaryAndTertiaryInverseDisabled.getNullable(
        this,
        jni$_.jint.type,
      ) as core$_.int;

  static final _id_textHintInverse = SystemColorsDynamicScheme._class
      .instanceFieldId(r'textHintInverse', r'I');

  /// from: `public final int textHintInverse`
  core$_.int get textHintInverse =>
      _id_textHintInverse.getNullable(this, jni$_.jint.type) as core$_.int;
}

final class $SystemColorsDynamicScheme$Type$
    extends jni$_.JType<SystemColorsDynamicScheme> {
  @jni$_.internal
  const $SystemColorsDynamicScheme$Type$();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Lio/qzz/deminearchiver/system_colors_android/SystemColorsDynamicScheme;';
}
