include:
  - package:deminearchiver_lints/analysis_options_flutter.yaml
  - package:deminearchiver_lints/app/loose.yaml
analyzer:
  exclude:
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**
