name: material_example
description: Material example.
version: 1.0.0
homepage: https://github.com/deminearchiver/dart-flutter-packages
repository: https://github.com/deminearchiver/dart-flutter-packages/tree/main/packages/material/example
issue_tracker: https://github.com/deminearchiver/dart-flutter-packages/issues
publish_to: none
resolution: workspace

environment:
  sdk: ^3.12.0
  flutter: ">=3.44.0"

dependencies:
  # SDK dependencies
  flutter:
    sdk: flutter

  # Path dependencies
  layout:
    path: ../../layout
  material:
    path: ../

  # Hosted dependencies
  collection: ^1.19.1
  cue: ^0.3.1
  dynamic_color_ffi: ^1.1.2
  flutter_markdown_plus: ^1.0.12
  flutter_shaders: ^0.1.3
  follow_the_leader: ^0.5.3
  freezed_annotation: ^3.1.0
  headless_widgets: ^0.0.7
  inspire_blur: ^0.4.0
  json_annotation: ^4.12.0
  linked_layouts: ^0.6.0
  markdown: ^7.3.1
  meta: ^1.18.0
  motor: ^1.1.0
  skeletonizer: ^2.1.3
  slang_flutter: ^4.18.0
  slang: ^4.18.0
  touch_targets: ^0.5.0
  vector_math: ^2.2.0
  widget_mask: ^1.0.0+0
  window_toolbox: ^0.0.7

dev_dependencies:
  # SDK dependencies
  flutter_test:
    sdk: flutter

  # Hosted dependencies
  build_runner: ^2.15.0
  deminearchiver_lints: ^2.1.2
  freezed: ^3.2.6-dev.1
  json_serializable: ^6.14.0
  slang_build_runner: ^4.18.0

flutter:
  uses-material-design: true
  assets:
    # Open Font Licenses
    - assets/fonts/googlesans/OFL.txt
    - assets/fonts/googlesanscode/OFL.txt
    - assets/fonts/googlesansflex/OFL.txt
    - assets/fonts/robotoflex/OFL.txt
    - assets/fonts/monaspace/OFL.txt
  fonts:
    - family: Google Sans
      fonts:
        - asset: assets/fonts/googlesans/GoogleSans-VariableFont_GRAD,opsz,wght.ttf
          style: normal
        - asset: assets/fonts/googlesans/GoogleSans-Italic-VariableFont_GRAD,opsz,wght.ttf
          style: italic
    - family: Google Sans Code
      fonts:
        - asset: assets/fonts/googlesanscode/GoogleSansCode[MONO,wght].ttf
          style: normal
        - asset: assets/fonts/googlesanscode/GoogleSansCode-Italic[MONO,wght].ttf
          style: italic
    - family: Google Sans Flex
      fonts:
        - asset: assets/fonts/googlesansflex/GoogleSansFlex-VariableFont_GRAD,ROND,opsz,slnt,wdth,wght.ttf
    - family: Monaspace Argon
      fonts:
        - asset: assets/fonts/monaspace/MonaspaceArgon-VariableFont_slnt,wdth,wght.ttf
    - family: Monaspace Krypton
      fonts:
        - asset: assets/fonts/monaspace/MonaspaceKrypton-VariableFont_slnt,wdth,wght.ttf
    - family: Monaspace Neon
      fonts:
        - asset: assets/fonts/monaspace/MonaspaceNeon-VariableFont_slnt,wdth,wght.ttf
    - family: Monaspace Radon
      fonts:
        - asset: assets/fonts/monaspace/MonaspaceRadon-VariableFont_slnt,wdth,wght.ttf
    - family: Monaspace Xenon
      fonts:
        - asset: assets/fonts/monaspace/MonaspaceXenon-VariableFont_slnt,wdth,wght.ttf
    - family: Roboto Flex
      fonts:
        - asset: assets/fonts/robotoflex/RobotoFlex-VariableFont_GRAD,XOPQ,XTRA,YOPQ,YTAS,YTDE,YTFI,YTLC,YTUC,opsz,slnt,wdth,wght.ttf
