name: material_example
description: Material example.
version: 1.0.0
homepage: https://github.com/deminearchiver/dart-flutter-packages
repository: https://github.com/deminearchiver/dart-flutter-packages/tree/main/packages/material/example
issue_tracker: https://github.com/deminearchiver/dart-flutter-packages/issues
publish_to: none
resolution: workspace

environment:
  sdk: ^3.11.0
  flutter: ">=3.41.0"

dependencies:
  # SDK dependencies
  flutter:
    sdk: flutter

  # Path dependencies
  layout:
    path: ../../layout
  material:
    path: ../

  # Hosted dependencies
  flutter_markdown_plus: ^1.0.7
  freezed_annotation: ^3.1.0
  json_annotation: ^4.11.0
  linked_layouts: ^0.5.0
  markdown: ^7.3.1
  meta: ^1.17.0
  motor: ^1.1.0
  slang: ^4.14.0
  slang_flutter: ^4.14.0
  follow_the_leader: ^0.5.3
  vector_math: ^2.2.0

dev_dependencies:
  # SDK dependencies
  flutter_test:
    sdk: flutter

  # Hosted dependencies
  build_runner: ^2.13.1
  deminearchiver_lints: ^2.1.2
  freezed: ^3.2.5
  json_serializable: ^6.13.1
  slang_build_runner: ^4.14.0

flutter:
  uses-material-design: true
  assets:
    # Open Font Licenses
    - assets/fonts/firacode/OFL.txt
    - assets/fonts/googlesans/OFL.txt
    - assets/fonts/googlesanscode/OFL.txt
    - assets/fonts/googlesansflex/OFL.txt
    - assets/fonts/robotoflex/OFL.txt
fonts:
  - family: Fira Code
    fonts:
      - asset: assets/fonts/firacode/FiraCode-VariableFont_wght.ttf
        style: normal
  - family: Google Sans
    fonts:
      - asset: assets/fonts/googlesans/GoogleSans-VariableFont_GRAD,opsz,wght.ttf
        style: normal
      - asset: assets/fonts/googlesans/GoogleSans-Italic-VariableFont_GRAD,opsz,wght.ttf
        style: italic
  - family: Google Sans Code
    fonts:
      - asset: assets/fonts/googlesanscode/GoogleSansCode-VariableFont_wght.ttf
        style: normal
      - asset: assets/fonts/googlesanscode/GoogleSansCode-Italic-VariableFont_wght.ttf
        style: italic
  - family: Google Sans Flex
    fonts:
      - asset: assets/fonts/googlesansflex/GoogleSansFlex-VariableFont_GRAD,ROND,opsz,slnt,wdth,wght.ttf
  - family: Monaspace Argon
    fonts:
      - asset: assets/fonts/monaspace/MonaspaceArgon-VariableFont.ttf
  - family: Roboto Flex
    fonts:
      - asset: assets/fonts/robotoflex/RobotoFlex-VariableFont_GRAD,XOPQ,XTRA,YOPQ,YTAS,YTDE,YTFI,YTLC,YTUC,opsz,slnt,wdth,wght.ttf
