name: system_colors
description: A Flutter plugin for obtaining system color schemes.
version: 0.2.0
homepage: https://github.com/deminearchiver/dart-flutter-packages
repository: https://github.com/deminearchiver/dart-flutter-packages/tree/main/packages/system_colors/system_colors
issue_tracker: https://github.com/deminearchiver/dart-flutter-packages/issues
resolution: workspace

environment:
  sdk: ^3.13.0
  flutter: ">=3.47.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.19.0
  system_colors_android: ^0.2.0
  system_colors_platform_interface: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  deminearchiver_lints: ^3.1.0

flutter:
  plugin:
    platforms:
      android:
        default_package: system_colors_android
