@file:Suppress("unused")

package io.qzz.deminearchiver.system_colors_android

import android.content.Context
import androidx.annotation.ColorInt
import androidx.annotation.Keep


@Keep
class SystemColorsDynamicScheme private constructor(
    @param:ColorInt @field:ColorInt @field:JvmField val primaryPaletteKeyColor: Int,
    @param:ColorInt @field:ColorInt @field:JvmField val secondaryPaletteKeyColor: Int,
    @param:ColorInt @field:ColorInt @field:JvmField val tertiaryPaletteKeyColor: Int,
    @param:ColorInt @field:ColorInt @field:JvmField val neutralPaletteKeyColor: Int,
    @param:ColorInt @field:ColorInt @field:JvmField val neutralVariantPaletteKeyColor: Int,
    @param:ColorInt @field:ColorInt @field:JvmField val errorPaletteKeyColor: Int,
    @param:ColorInt @field:ColorInt @field:JvmField val background: Int,
    @param:ColorInt @field:ColorInt @field:JvmField val onBackground: Int,
    @param:ColorInt @field:ColorInt @field:JvmField val surface: Int,
    @param:ColorInt @field:ColorInt @field:JvmField val surfaceDim: Int,
    @param:ColorInt @field:ColorInt @field:JvmField val surfaceBright: Int,
    @param:ColorInt @field:ColorInt @field:JvmField val surfaceContainerLowest: Int,
    @param:ColorInt @field:ColorInt @field:JvmField val surfaceContainerLow: Int,
    @param:ColorInt @field:ColorInt @field:JvmField val surfaceContainer: Int,
    @param:ColorInt @field:ColorInt @field:JvmField val surfaceContainerHigh: Int,
    @param:ColorInt @field:ColorInt @field:JvmField val surfaceContainerHighest: Int,
    @param:ColorInt @field:ColorInt @field:JvmField val onSurface: Int,
    @param:ColorInt @field:ColorInt @field:JvmField val surfaceVariant: Int,
    @param:ColorInt @field:ColorInt @field:JvmField val onSurfaceVariant: Int,
    @param:ColorInt @field:ColorInt @field:JvmField val outline: Int,
    @param:ColorInt @field:ColorInt @field:JvmField val outlineVariant: Int,
    @param:ColorInt @field:ColorInt @field:JvmField val inverseSurface: Int,
    @param:ColorInt @field:ColorInt @field:JvmField val inverseOnSurface: Int,
    @param:ColorInt @field:ColorInt @field:JvmField val shadow: Int,
    @param:ColorInt @field:ColorInt @field:JvmField val scrim: Int,
    @param:ColorInt @field:ColorInt @field:JvmField val surfaceTint: Int,
    @param:ColorInt @field:ColorInt @field:JvmField val primary: Int,
    @param:ColorInt @field:ColorInt @field:JvmField val primaryDim: Int,
    @param:ColorInt @field:ColorInt @field:JvmField val onPrimary: Int,
    @param:ColorInt @field:ColorInt @field:JvmField val primaryContainer: Int,
    @param:ColorInt @field:ColorInt @field:JvmField val onPrimaryContainer: Int,
    @param:ColorInt @field:ColorInt @field:JvmField val primaryFixed: Int,
    @param:ColorInt @field:ColorInt @field:JvmField val primaryFixedDim: Int,
    @param:ColorInt @field:ColorInt @field:JvmField val onPrimaryFixed: Int,
    @param:ColorInt @field:ColorInt @field:JvmField val onPrimaryFixedVariant: Int,
    @param:ColorInt @field:ColorInt @field:JvmField val inversePrimary: Int,
    @param:ColorInt @field:ColorInt @field:JvmField val secondary: Int,
    @param:ColorInt @field:ColorInt @field:JvmField val secondaryDim: Int,
    @param:ColorInt @field:ColorInt @field:JvmField val onSecondary: Int,
    @param:ColorInt @field:ColorInt @field:JvmField val secondaryContainer: Int,
    @param:ColorInt @field:ColorInt @field:JvmField val onSecondaryContainer: Int,
    @param:ColorInt @field:ColorInt @field:JvmField val secondaryFixed: Int,
    @param:ColorInt @field:ColorInt @field:JvmField val secondaryFixedDim: Int,
    @param:ColorInt @field:ColorInt @field:JvmField val onSecondaryFixed: Int,
    @param:ColorInt @field:ColorInt @field:JvmField val onSecondaryFixedVariant: Int,
    @param:ColorInt @field:ColorInt @field:JvmField val tertiary: Int,
    @param:ColorInt @field:ColorInt @field:JvmField val tertiaryDim: Int,
    @param:ColorInt @field:ColorInt @field:JvmField val onTertiary: Int,
    @param:ColorInt @field:ColorInt @field:JvmField val tertiaryContainer: Int,
    @param:ColorInt @field:ColorInt @field:JvmField val onTertiaryContainer: Int,
    @param:ColorInt @field:ColorInt @field:JvmField val tertiaryFixed: Int,
    @param:ColorInt @field:ColorInt @field:JvmField val tertiaryFixedDim: Int,
    @param:ColorInt @field:ColorInt @field:JvmField val onTertiaryFixed: Int,
    @param:ColorInt @field:ColorInt @field:JvmField val onTertiaryFixedVariant: Int,
    @param:ColorInt @field:ColorInt @field:JvmField val error: Int,
    @param:ColorInt @field:ColorInt @field:JvmField val errorDim: Int,
    @param:ColorInt @field:ColorInt @field:JvmField val onError: Int,
    @param:ColorInt @field:ColorInt @field:JvmField val errorContainer: Int,
    @param:ColorInt @field:ColorInt @field:JvmField val onErrorContainer: Int,
    @param:ColorInt @field:ColorInt @field:JvmField val controlActivated: Int,
    @param:ColorInt @field:ColorInt @field:JvmField val controlNormal: Int,
    @param:ColorInt @field:ColorInt @field:JvmField val controlHighlight: Int,
    @param:ColorInt @field:ColorInt @field:JvmField val textPrimaryInverse: Int,
    @param:ColorInt @field:ColorInt @field:JvmField val textSecondaryAndTertiaryInverse: Int,
    @param:ColorInt @field:ColorInt @field:JvmField val textPrimaryInverseDisableOnly: Int,
    @param:ColorInt @field:ColorInt @field:JvmField val textSecondaryAndTertiaryInverseDisabled: Int,
    @param:ColorInt @field:ColorInt @field:JvmField val textHintInverse: Int,
) {
    private constructor(
        @ColorInt sentinel: Int,
        @ColorInt primaryPaletteKeyColor: Int = sentinel,
        @ColorInt secondaryPaletteKeyColor: Int = sentinel,
        @ColorInt tertiaryPaletteKeyColor: Int = sentinel,
        @ColorInt neutralPaletteKeyColor: Int = sentinel,
        @ColorInt neutralVariantPaletteKeyColor: Int = sentinel,
        @ColorInt errorPaletteKeyColor: Int = sentinel,
        @ColorInt background: Int = sentinel,
        @ColorInt onBackground: Int = sentinel,
        @ColorInt surface: Int = sentinel,
        @ColorInt surfaceDim: Int = sentinel,
        @ColorInt surfaceBright: Int = sentinel,
        @ColorInt surfaceContainerLowest: Int = sentinel,
        @ColorInt surfaceContainerLow: Int = sentinel,
        @ColorInt surfaceContainer: Int = sentinel,
        @ColorInt surfaceContainerHigh: Int = sentinel,
        @ColorInt surfaceContainerHighest: Int = sentinel,
        @ColorInt onSurface: Int = sentinel,
        @ColorInt surfaceVariant: Int = sentinel,
        @ColorInt onSurfaceVariant: Int = sentinel,
        @ColorInt outline: Int = sentinel,
        @ColorInt outlineVariant: Int = sentinel,
        @ColorInt inverseSurface: Int = sentinel,
        @ColorInt inverseOnSurface: Int = sentinel,
        @ColorInt shadow: Int = sentinel,
        @ColorInt scrim: Int = sentinel,
        @ColorInt surfaceTint: Int = sentinel,
        @ColorInt primary: Int = sentinel,
        @ColorInt primaryDim: Int = sentinel,
        @ColorInt onPrimary: Int = sentinel,
        @ColorInt primaryContainer: Int = sentinel,
        @ColorInt onPrimaryContainer: Int = sentinel,
        @ColorInt primaryFixed: Int = sentinel,
        @ColorInt primaryFixedDim: Int = sentinel,
        @ColorInt onPrimaryFixed: Int = sentinel,
        @ColorInt onPrimaryFixedVariant: Int = sentinel,
        @ColorInt inversePrimary: Int = sentinel,
        @ColorInt secondary: Int = sentinel,
        @ColorInt secondaryDim: Int = sentinel,
        @ColorInt onSecondary: Int = sentinel,
        @ColorInt secondaryContainer: Int = sentinel,
        @ColorInt onSecondaryContainer: Int = sentinel,
        @ColorInt secondaryFixed: Int = sentinel,
        @ColorInt secondaryFixedDim: Int = sentinel,
        @ColorInt onSecondaryFixed: Int = sentinel,
        @ColorInt onSecondaryFixedVariant: Int = sentinel,
        @ColorInt tertiary: Int = sentinel,
        @ColorInt tertiaryDim: Int = sentinel,
        @ColorInt onTertiary: Int = sentinel,
        @ColorInt tertiaryContainer: Int = sentinel,
        @ColorInt onTertiaryContainer: Int = sentinel,
        @ColorInt tertiaryFixed: Int = sentinel,
        @ColorInt tertiaryFixedDim: Int = sentinel,
        @ColorInt onTertiaryFixed: Int = sentinel,
        @ColorInt onTertiaryFixedVariant: Int = sentinel,
        @ColorInt error: Int = sentinel,
        @ColorInt errorDim: Int = sentinel,
        @ColorInt onError: Int = sentinel,
        @ColorInt errorContainer: Int = sentinel,
        @ColorInt onErrorContainer: Int = sentinel,
        @ColorInt controlActivated: Int = sentinel,
        @ColorInt controlNormal: Int = sentinel,
        @ColorInt controlHighlight: Int = sentinel,
        @ColorInt textPrimaryInverse: Int = sentinel,
        @ColorInt textSecondaryAndTertiaryInverse: Int = sentinel,
        @ColorInt textPrimaryInverseDisableOnly: Int = sentinel,
        @ColorInt textSecondaryAndTertiaryInverseDisabled: Int = sentinel,
        @ColorInt textHintInverse: Int = sentinel,
    ) : this(
        primaryPaletteKeyColor = primaryPaletteKeyColor,
        secondaryPaletteKeyColor = secondaryPaletteKeyColor,
        tertiaryPaletteKeyColor = tertiaryPaletteKeyColor,
        neutralPaletteKeyColor = neutralPaletteKeyColor,
        neutralVariantPaletteKeyColor = neutralVariantPaletteKeyColor,
        errorPaletteKeyColor = errorPaletteKeyColor,
        background = background,
        onBackground = onBackground,
        surface = surface,
        surfaceDim = surfaceDim,
        surfaceBright = surfaceBright,
        surfaceContainerLowest = surfaceContainerLowest,
        surfaceContainerLow = surfaceContainerLow,
        surfaceContainer = surfaceContainer,
        surfaceContainerHigh = surfaceContainerHigh,
        surfaceContainerHighest = surfaceContainerHighest,
        onSurface = onSurface,
        surfaceVariant = surfaceVariant,
        onSurfaceVariant = onSurfaceVariant,
        outline = outline,
        outlineVariant = outlineVariant,
        inverseSurface = inverseSurface,
        inverseOnSurface = inverseOnSurface,
        shadow = shadow,
        scrim = scrim,
        surfaceTint = surfaceTint,
        primary = primary,
        primaryDim = primaryDim,
        onPrimary = onPrimary,
        primaryContainer = primaryContainer,
        onPrimaryContainer = onPrimaryContainer,
        primaryFixed = primaryFixed,
        primaryFixedDim = primaryFixedDim,
        onPrimaryFixed = onPrimaryFixed,
        onPrimaryFixedVariant = onPrimaryFixedVariant,
        inversePrimary = inversePrimary,
        secondary = secondary,
        secondaryDim = secondaryDim,
        onSecondary = onSecondary,
        secondaryContainer = secondaryContainer,
        onSecondaryContainer = onSecondaryContainer,
        secondaryFixed = secondaryFixed,
        secondaryFixedDim = secondaryFixedDim,
        onSecondaryFixed = onSecondaryFixed,
        onSecondaryFixedVariant = onSecondaryFixedVariant,
        tertiary = tertiary,
        tertiaryDim = tertiaryDim,
        onTertiary = onTertiary,
        tertiaryContainer = tertiaryContainer,
        onTertiaryContainer = onTertiaryContainer,
        tertiaryFixed = tertiaryFixed,
        tertiaryFixedDim = tertiaryFixedDim,
        onTertiaryFixed = onTertiaryFixed,
        onTertiaryFixedVariant = onTertiaryFixedVariant,
        error = error,
        errorDim = errorDim,
        onError = onError,
        errorContainer = errorContainer,
        onErrorContainer = onErrorContainer,
        controlActivated = controlActivated,
        controlNormal = controlNormal,
        controlHighlight = controlHighlight,
        textPrimaryInverse = textPrimaryInverse,
        textSecondaryAndTertiaryInverse = textSecondaryAndTertiaryInverse,
        textPrimaryInverseDisableOnly = textPrimaryInverseDisableOnly,
        textSecondaryAndTertiaryInverseDisabled = textSecondaryAndTertiaryInverseDisabled,
        textHintInverse = textHintInverse,
    )

    companion object {
        @JvmStatic
        fun empty(@ColorInt sentinel: Int) = SystemColorsDynamicScheme(sentinel)


        @JvmStatic
        fun fromContext(context: Context, isDark: Boolean, @ColorInt sentinel: Int) =
            if (isDark) darkFromContext(context, sentinel) else lightFromContext(context, sentinel)

        @JvmStatic
        fun lightFromContext(context: Context, @ColorInt sentinel: Int): SystemColorsDynamicScheme {
            return empty(sentinel)
        }

        @JvmStatic
        fun darkFromContext(context: Context, @ColorInt sentinel: Int): SystemColorsDynamicScheme {
            return empty(sentinel)
        }
    }
}
